"""Curated Phase 5 (version 3.0) standard lessons for non-golden chapters 3-6 points.

Every non-golden knowledge point gets five authored resources (intuition,
definition, formula, worked example, common error) plus the shared summary and
source reference rows, so the student-facing learning page never falls back to
a bare taxonomy description.

The prose is project-authored original Chinese teaching content. OpenStax is
recorded as a scope reference only, never copied; attribution stays in SQL via
the Phase 5 source document.
"""

# OpenStax Calculus reference per knowledge point code (scope reference only).
STANDARD_CHAPTER_REF = {
    "fermat-theorem": "第 4 章 Applications of Derivatives",
    "cauchy-mvt": "第 4 章 Applications of Derivatives",
    "monotonicity-derivative": "第 4 章 Applications of Derivatives",
    "local-extrema": "第 4 章 Applications of Derivatives",
    "global-extrema": "第 4 章 Applications of Derivatives",
    "optimization-modeling": "第 4 章 Applications of Derivatives",
    "concavity": "第 4 章 Applications of Derivatives",
    "inflection-points": "第 4 章 Applications of Derivatives",
    "curve-asymptotes": "第 4 章 Applications of Derivatives",
    "curvature": "第 4 章 Applications of Derivatives",
    "taylor-formula": "Volume 2 第 6 章 Power Series",
    "maclaurin-expansions": "Volume 2 第 6 章 Power Series",
    "differential-approximation": "第 4 章 Applications of Derivatives",
    "root-approximation": "第 4 章 Applications of Derivatives",
    "indefinite-properties": "第 5 章 Integration",
    "basic-integral-table": "第 5 章 Integration",
    "direct-integration": "第 5 章 Integration",
    "substitution-second-kind": "第 7 章 Techniques of Integration",
    "rational-integration": "第 7 章 Techniques of Integration",
    "trigonometric-integration": "第 7 章 Techniques of Integration",
    "radical-integration": "第 7 章 Techniques of Integration",
    "integration-strategy": "第 7 章 Techniques of Integration",
    "indefinite-integral-review": "第 7 章 Techniques of Integration",
    "riemann-sum": "第 5 章 Integration",
    "definite-integral-properties": "第 5 章 Integration",
    "integral-mean-value": "第 5 章 Integration",
    "definite-substitution": "第 5 章 Integration",
    "definite-parts": "第 7 章 Techniques of Integration",
    "symmetry-periodicity-integrals": "第 5 章 Integration",
    "improper-infinite-interval": "第 7 章 Techniques of Integration",
    "improper-unbounded-function": "第 7 章 Techniques of Integration",
    "improper-convergence": "第 7 章 Techniques of Integration",
    "area-parametric-polar": "Volume 2 第 7 章 Parametric Equations and Polar Coordinates",
    "volume-slicing": "第 6 章 Applications of Integration",
    "surface-area-revolution": "第 6 章 Applications of Integration",
    "work-by-variable-force": "第 6 章 Applications of Integration",
    "fluid-force": "第 6 章 Applications of Integration",
    "average-value-function": "第 5 章 Integration",
    "integral-application-modeling": "第 6 章 Applications of Integration",
}

# One-line catalogue description per standard point (shown in the graph/list view).
DESCRIPTIONS = {
    "fermat-theorem": "可导极值点处导数为零，是寻找极值的必要条件。",
    "cauchy-mvt": "两个函数平均变化率之比等于某点导数之比，是洛必达法则的证明基础。",
    "monotonicity-derivative": "用一阶导数符号判定函数在区间上的增减。",
    "local-extrema": "用一阶导数变号或二阶导数符号判定局部极大与极小。",
    "global-extrema": "在闭区间上比较驻点、不可导点与端点取值求最值。",
    "optimization-modeling": "把实际约束代入目标函数，化为一元最值问题。",
    "concavity": "用二阶导数符号判定曲线弧相对切线的上下位置。",
    "inflection-points": "找出凹凸性发生改变的点，必须检查二阶导数是否变号。",
    "curve-asymptotes": "求水平、铅直与斜渐近线以刻画曲线远处的走向。",
    "curvature": "用一阶、二阶导数刻画曲线的弯曲程度与曲率半径。",
    "taylor-formula": "用带拉格朗日余项的多项式在一点附近逼近函数。",
    "maclaurin-expansions": "记忆常用函数的麦克劳林展开并用于极限与近似计算。",
    "differential-approximation": "用微分（线性主部）近似函数增量并估计误差。",
    "root-approximation": "用二分法或牛顿切线法求方程根的近似值。",
    "indefinite-properties": "不定积分的线性性质与逐项积分方法。",
    "basic-integral-table": "常用基本积分公式及其适用条件。",
    "direct-integration": "经恒等变形后直接查表完成积分。",
    "substitution-second-kind": "用三角代换或根式代换消去根号完成积分。",
    "rational-integration": "用部分分式把有理函数化为可积的简单分式。",
    "trigonometric-integration": "按奇偶结构与万能代换处理三角有理式积分。",
    "radical-integration": "通过整体换元把简单无理函数化为有理函数。",
    "integration-strategy": "按化简、凑微分、分部、代换的顺序选择积分方法。",
    "indefinite-integral-review": "综合运用多种积分方法处理复合结构的被积函数。",
    "riemann-sum": "用分割、取点、求和逼近曲边梯形的面积。",
    "definite-integral-properties": "定积分的线性、区间可加、保号与估值性质。",
    "integral-mean-value": "存在等效高度使矩形面积等于积分值。",
    "definite-substitution": "定积分换元必须同步更换积分上下限。",
    "definite-parts": "带上下限的分部积分公式与边界项代入。",
    "symmetry-periodicity-integrals": "利用奇偶性与周期性简化定积分计算。",
    "improper-infinite-interval": "用极限定义无穷区间上的反常积分。",
    "improper-unbounded-function": "处理被积函数无界（瑕点）的反常积分。",
    "improper-convergence": "用 p 积分与比较判别法判断反常积分敛散性。",
    "area-parametric-polar": "参数方程与极坐标下曲边区域的面积公式。",
    "volume-slicing": "以平行截面面积的积分计算立体体积。",
    "surface-area-revolution": "用弧微元计算旋转曲面的侧面积。",
    "work-by-variable-force": "变力沿直线做功与抽水做功的积分模型。",
    "fluid-force": "用压强随深度变化计算液体对铅直薄板的静压力。",
    "average-value-function": "用积分除以区间长度定义函数的平均值。",
    "integral-application-modeling": "用微元法统一处理面积、体积、功等综合问题。",
}

STANDARD = {
    "fermat-theorem": {
        "intuition": "函数在局部最高点或最低点处，如果曲线光滑（可导），切线必定是水平的：否则沿着切线方向还能再升或再降，与“最高、最低”矛盾。",
        "definition": "设 $f$ 在点 $x_0$ 的某邻域内有定义且在 $x_0$ 处可导。若 $f(x_0)$ 是该邻域内的极大值或极小值，则 $$f'(x_0)=0$$ 称导数为零的点为驻点。费马引理只给出极值的必要条件：驻点未必是极值点（如 $y=x^3$ 在 $x=0$）。",
        "formula": "$$f'(x_0)=0\\;\\Rightarrow\\;x_0\\text{ 为驻点}$$",
        "example": "$f(x)=x^3-3x$ 的驻点：$f'(x)=3x^2-3=0$ 解得 $x=\\pm1$。$f(1)=-2$ 是极小值、$f(-1)=2$ 是极大值，两个驻点恰好都是极值点；但注意驻点与极值点并不总是一一对应，需再用单调性或二阶导数判定。",
        "error": "常见错误：①把费马引理当作充分条件，见到 $f'(x_0)=0$ 就断言取到极值；②忽略“可导”前提——极值也可能出现在不可导点（如 $y=|x|$ 在 $x=0$ 取极小但不可导），此时 $f'(x_0)=0$ 的结论不适用。",
    },
    "cauchy-mvt": {
        "intuition": "把曲线看作参数式 $x=g(t)、y=f(t)$，拉格朗日中值定理的割线平行切线结论翻译过来就是柯西中值定理：两个函数各自的平均变化率之比等于某一点瞬时变化率之比。",
        "definition": "设 $f$、$g$ 都在 $[a,b]$ 上连续、在 $(a,b)$ 内可导，且对任意 $x\\in(a,b)$ 有 $g'(x)\\ne0$，则存在 $\\xi\\in(a,b)$ 使得 $$\\frac{f(b)-f(a)}{g(b)-g(a)}=\\frac{f'(\\xi)}{g'(\\xi)}$$ 条件 $g'\\ne0$ 保证分母不为零且 $g(b)\\ne g(a)$。它是证明洛必达法则的主要工具。",
        "formula": "$$\\frac{f(b)-f(a)}{g(b)-g(a)}=\\frac{f'(\\xi)}{g'(\\xi)},\\quad\\xi\\in(a,b)$$",
        "example": "设 $f(x)=x^2$、$g(x)=\\ln x$，在 $[1,e]$ 上：$\\frac{f(e)-f(1)}{g(e)-g(1)}=\\frac{e^2-1}{1}=e^2-1$，而 $\\frac{f'(x)}{g'(x)}=\\frac{2x}{1/x}=2x^2$，令 $2\\xi^2=e^2-1$ 得 $\\xi=\\sqrt{\\frac{e^2-1}{2}}\\approx1.46\\in(1,e)$，与定理一致。",
        "error": "常见错误：①对 $f$、$g$ 分别用拉格朗日中值定理再相除——两次定理给出的 $\\xi$ 未必是同一点；②不验证 $g'(x)\\ne0$ 就使用；③误以为可以对三个函数写类似的“比值中值”公式。",
    },
    "monotonicity-derivative": {
        "intuition": "导数是函数的瞬时速度：速度始终为正，函数就一直上升；始终为负就下降。个别点上速度为零不影响整体趋势，就像行走中瞬间停顿不会改变前进方向。",
        "definition": "设 $f$ 在 $[a,b]$ 上连续，在 $(a,b)$ 内可导。若在 $(a,b)$ 内 $f'(x)>0$，则 $f$ 在 $[a,b]$ 上单调增加；若 $f'(x)<0$，则单调减少。若只在有限个点处 $f'=0$ 而其余点保持同号，单调性结论仍然成立（如 $y=x^3$）。",
        "formula": "$$f'(x)>0\\Rightarrow\\text{增};\\quad f'(x)<0\\Rightarrow\\text{减}$$",
        "example": "讨论 $f(x)=x^3-3x$ 的单调性。$f'(x)=3(x-1)(x+1)$：当 $x<-1$ 或 $x>1$ 时 $f'>0$，函数在 $(-\\infty,-1]$、$[1,+\\infty)$ 上增加；当 $-1<x<1$ 时 $f'<0$，在 $[-1,1]$ 上减少。符号表是规范写法：列出驻点，逐区间判号。",
        "error": "常见错误：①在包含不可导点的区间上只看导数符号，忽略分段讨论；②把 $f'(x_0)>0$ 当成 $x_0$ 附近单调的必要条件（严格单调允许孤立驻点）；③忘记单调区间不能随意用并集连接——本题在 $x<-1$、$-1<x<1$、$x>1$ 三段上导数符号不同，必须分开写。",
    },
    "local-extrema": {
        "intuition": "极值是“小山头、小洼地”：只与附近比较，与全局无关。寻找方法是先找可疑点（驻点与不可导点），再看函数经过该点时是否发生升降切换。",
        "definition": "设 $f$ 在 $x_0$ 的某邻域内有定义。若对该邻域内一切 $x$ 有 $f(x)\\le f(x_0)$（或 $\\ge$），则称 $f(x_0)$ 为极大值（或极小值）。判定法：①第一充分条件——$f'$ 在 $x_0$ 两侧由正变负取极大，由负变正取极小，不变号则不是极值；②第二充分条件——$f'(x_0)=0$ 且 $f''(x_0)<0$ 取极大，$f''(x_0)>0$ 取极小，$f''(x_0)=0$ 时失效需改用第一判据。",
        "formula": "$$f'(x_0)=0,\\;f''(x_0)<0\\Rightarrow\\text{极大};\\quad f'(x_0)=0,\\;f''(x_0)>0\\Rightarrow\\text{极小}$$",
        "example": "$f(x)=x^3-3x$：驻点 $x=\\pm1$。$f''(x)=6x$，$f''(-1)=-6<0$ 故 $x=-1$ 取极大值 $f(-1)=2$；$f''(1)=6>0$ 故 $x=1$ 取极小值 $f(1)=-2$。与单调性分析结论一致。",
        "error": "常见错误：①漏掉不可导的极值可疑点；②$f''(x_0)=0$ 时强行下结论（如 $y=x^4$ 在 $0$ 处 $f''=0$ 但取极小）；③把极大值与最大值混为一谈——极大值可能小于另一点的极小值。",
    },
    "global-extrema": {
        "intuition": "闭区间上的连续曲线一定有最高点和最低点，它们只可能藏在三类位置：驻点、不可导点、区间端点。把候选点的函数值全部算出来比较即可。",
        "definition": "若 $f$ 在闭区间 $[a,b]$ 上连续，则必取得最大值与最小值（最值定理）。求法：①求出 $(a,b)$ 内全部驻点与不可导点；②计算这些点与端点 $a、b$ 处的函数值；③比较得最大、最小。开区间或无穷区间上的最值还需结合单调性与极限行为判断是否存在。",
        "formula": "$$M=\\max\\{f(\\text{候选点}),\\,f(a),\\,f(b)\\},\\quad m=\\min\\{\\cdots\\}$$",
        "example": "$f(x)=x^3-3x$ 在 $[0,2]$ 上：驻点 $x=1$（$x=-1$ 不在区间内），候选值 $f(0)=0$、$f(1)=-2$、$f(2)=2$。故最大值 $2$（在 $x=2$），最小值 $-2$（在 $x=1$）。注意最大值出现在端点而非驻点。",
        "error": "常见错误：①忘记比较端点值；②把区间外或不在候选集中的点纳入比较；③在开区间上直接套“候选点比较法”却不验证极限端的行为——开区间连续函数可能无最值（如 $y=x$ 在 $(0,1)$）。",
    },
    "optimization-modeling": {
        "intuition": "最优化问题的核心是“设变量、列目标、找约束、化为一元”：先用几何或物理关系把约束条件代入目标函数，问题就归结为求一元函数的最值。",
        "definition": "建模步骤：①设自变量并注明范围；②用自变量表示目标量，写出目标函数；③利用约束消元，把目标函数化为一元函数；④求导找驻点与不可导点，结合实际问题端点或边界，判定最值；⑤检验结果是否合乎实际（长度为正、整数约束等）并作答。",
        "formula": "$$\\text{实际问题最值}\\;\\Leftarrow\\;f'(x_0)=0\\text{ 且单调性发生切换}$$",
        "example": "用长 $l$ 的铁丝围成矩形，何时面积最大？设一边为 $x$，另一边为 $\\frac{l}{2}-x$，面积 $S(x)=x\\left(\\frac{l}{2}-x\\right)$，$0<x<\\frac{l}{2}$。$S'(x)=\\frac{l}{2}-2x=0$ 得 $x=\\frac{l}{4}$，即正方形时面积最大 $S=\\frac{l^2}{16}$。端点处 $S\\to0$，故驻点确为最大值点。",
        "error": "常见错误：①目标函数仍含两个变量就开始求导；②忽略自变量实际范围；③实际问题中驻点唯一时未说明“为何该驻点就是最值点”（可由问题背景或单调性保证）；④漏写单位与实际检验。",
    },
    "concavity": {
        "intuition": "一阶导数描述升降，二阶导数描述升降的“加速度”：$f''>0$ 时切线斜率越来越大，曲线像碗底一样向上弯（凹/下凸）；$f''<0$ 时向下弯（凸/上凸）。",
        "definition": "设 $f$ 在 $[a,b]$ 上连续、$(a,b)$ 内二阶可导。若在 $(a,b)$ 内 $f''(x)>0$，则曲线弧位于其任一点切线的上方，称图形是凹的（向上凹）；若 $f''(x)<0$，则弧位于切线下方，称图形是凸的。判别只需求 $f''$ 的符号区间。",
        "formula": "$$f''(x)>0\\Rightarrow\\text{凹（上凹）};\\quad f''(x)<0\\Rightarrow\\text{凸（上凸）}$$",
        "example": "$y=x^3$：$y''=6x$。当 $x>0$ 时 $y''>0$ 图形凹；$x<0$ 时 $y''<0$ 图形凸。凹凸性在 $x=0$ 两侧发生切换，说明原点是拐点候选。",
        "error": "常见错误：①凹凸的方向术语在不同教材中相反，答题时应同时给出 $f''$ 的符号以避免歧义；②把凹凸性与单调性混淆——$f$ 可能一边递减一边是凹的；③在 $f''$ 不存在的点附近不讨论符号就直接下结论。",
    },
    "inflection-points": {
        "intuition": "拐点是曲线“弯向改变”的转折处：弯曲方向在此处切换，对应的二阶导数通常为零或不存在。",
        "definition": "若连续曲线 $y=f(x)$ 在点 $\\left(x_0,f(x_0)\\right)$ 两侧凹凸性相反，则称该点为拐点。求法：①求 $f''(x)=0$ 的根及 $f''$ 不存在的点；②逐一检查这些点两侧 $f''$ 是否变号；③变号者即拐点，函数在该点必须连续。$f''(x_0)=0$ 只是必要线索，不是充分条件。",
        "formula": "$$f''\\text{ 在 }x_0\\text{ 两侧变号}\\;\\Rightarrow\\;\\left(x_0,f(x_0)\\right)\\text{ 为拐点}$$",
        "example": "$y=x^4$：$y''=12x^2$，在 $x=0$ 处 $y''=0$，但两侧恒有 $y''\\ge0$ 不变号，故 $(0,0)$ 不是拐点；而 $y=x^3$ 的 $y''=6x$ 在 $0$ 两侧变号，$(0,0)$ 是拐点。两例对照说明必须检查变号。",
        "error": "常见错误：①见 $f''(x_0)=0$ 就宣布拐点（$y=x^4$ 反例）；②把拐点横坐标当成拐点——拐点是平面上的点，应写 $(x_0,f(x_0))$；③忽略 $f''$ 不存在但凹凸改变的点（如 $y=\\sqrt[3]{x}$ 在 $0$ 处）。",
    },
    "curve-asymptotes": {
        "intuition": "渐近线描述曲线奔向无穷远时的“路线”：水平渐近线是远处趋向的固定高度，铅直渐近线是无界奔逃的竖直屏障，斜渐近线则是沿一条直线方向前进。",
        "definition": "①水平渐近线：若 $\\lim_{x\\to+\\infty}f(x)=b$ 或 $\\lim_{x\\to-\\infty}f(x)=b$，则 $y=b$ 是水平渐近线；②铅直渐近线：若 $\\lim_{x\\to a^+}f(x)=\\infty$ 或 $\\lim_{x\\to a^-}f(x)=\\infty$，则 $x=a$ 是铅直渐近线（$a$ 常见于分母零点、无界点）；③斜渐近线：若 $k=\\lim_{x\\to\\infty}\\frac{f(x)}{x}$、$b=\\lim_{x\\to\\infty}\\left[f(x)-kx\\right]$ 都存在且 $k\\ne0$，则 $y=kx+b$ 是斜渐近线。",
        "formula": "$$y=b,\\quad x=a,\\quad y=kx+b\\;\\left(k=\\lim\\frac{f(x)}{x},\\;b=\\lim\\left[f(x)-kx\\right]\\right)$$",
        "example": "$y=\\frac{x^2+1}{x}$：$x\\to0^\\pm$ 时 $y\\to\\pm\\infty$，铅直渐近线 $x=0$；$\\frac{y}{x}=\\frac{x^2+1}{x^2}\\to1$ 得 $k=1$，$y-x=\\frac1x\\to0$ 得 $b=0$，斜渐近线 $y=x$。同一函数两个方向都可能有渐近线，必须分别检查。",
        "error": "常见错误：①只查 $x\\to+\\infty$ 漏掉 $x\\to-\\infty$（两方向渐近线可能不同）；②求 $b$ 时忘记先减去 $kx$；③把无界但不趋于直线的情形（如 $y=x^2$）硬找渐近线；④分母零点处若分子同时为零（可去间断）并不是铅直渐近线。",
    },
    "curvature": {
        "intuition": "曲率衡量曲线“弯得有多急”：同样走一单位弧长，方向转得越多，弯得越厉害。直线的方向不变，曲率为零；半径越小的圆弯得越急，曲率越大。",
        "definition": "设曲线 $y=f(x)$ 二阶可导，曲率定义为 $$K=\\frac{|y''|}{\\left(1+y'^2\\right)^{3/2}}$$ 曲率的倒数 $R=\\frac1K$ 称曲率半径；曲率半径的倒数越大弯越急。参数方程 $x=x(t)、y=y(t)$ 下 $K=\\frac{|x'y''-y'x''|}{\\left(x'^2+y'^2\\right)^{3/2}}$。",
        "formula": "$$K=\\frac{|y''|}{(1+y'^2)^{3/2}},\\quad R=\\frac{1}{K}$$",
        "example": "半径为 $R_0$ 的圆：参数式 $x=R_0\\cos t$、$y=R_0\\sin t$ 代入公式得 $K=\\frac{R_0^2}{R_0^3}=\\frac{1}{R_0}$，即圆上任一点曲率相同且等于半径的倒数，与直觉完全一致。直线 $y=ax+b$ 的 $y''=0$，故 $K=0$。",
        "error": "常见错误：①忘记分母的 $\\frac32$ 次幂或漏掉绝对值；②把曲率与斜率、倾角混为一谈——斜率描述方向，曲率描述方向变化率；③工程问题（弯道限速、砂轮打磨）中忘记用曲率半径换算。",
    },
    "taylor-formula": {
        "intuition": "泰勒公式用多项式“临摹”函数：在一点处让两者的函数值、一阶导数、二阶导数……直到 $n$ 阶导数都相等，得到的 $n$ 次多项式在该点附近与函数高度贴合，贴合误差由余项刻画。",
        "definition": "设 $f$ 在含 $x_0$ 的区间内有直到 $n+1$ 阶导数，则 $$f(x)=\\sum_{k=0}^{n}\\frac{f^{(k)}(x_0)}{k!}(x-x_0)^k+R_n(x)$$ 其中拉格朗日余项 $$R_n(x)=\\frac{f^{(n+1)}(\\xi)}{(n+1)!}(x-x_0)^{n+1},\\quad\\xi\\text{ 介于 }x_0\\text{ 与 }x\\text{ 之间}$$ 当 $x_0=0$ 时称为麦克劳林公式。余项给出误差的精确表达，是近似计算与极限求解的利器。",
        "formula": "$$f(x)=f(x_0)+f'(x_0)(x-x_0)+\\cdots+\\frac{f^{(n)}(x_0)}{n!}(x-x_0)^n+R_n(x)$$",
        "example": "求 $e^x$ 的 $n$ 阶麦克劳林公式。$f^{(k)}(0)=1$，故 $e^x=1+x+\\frac{x^2}{2!}+\\cdots+\\frac{x^n}{n!}+\\frac{e^{\\xi}}{(n+1)!}x^{n+1}$。取 $x=1$ 得 $e\\approx1+1+\\frac12+\\cdots+\\frac1{n!}$，误差不超过 $\\frac{3}{(n+1)!}$（因 $e^\\xi<3$），$n=8$ 时误差已小于 $10^{-5}$。",
        "error": "常见错误：①系数除以阶乘 $k!$ 漏写；②余项写错位置（$\\xi$ 介于 $x_0$ 与 $x$ 之间而不是区间端点）；③用低阶展开求极限时余项阶数不够，导致化简后仍含未定型；④把泰勒公式与幂级数展开混为一谈——公式是有限项加余项，级数还需讨论收敛域。",
    },
    "maclaurin-expansions": {
        "intuition": "五个常用麦克劳林展开是“标准件”：记住 $e^x$、$\\sin x$、$\\cos x$、$\\ln(1+x)$、$(1+x)^\\alpha$ 的展开式与阶数，复杂极限与近似计算就能通过替换、拼接快速完成。",
        "definition": "常用展开（$x\\to0$ 附近）：$$e^x=1+x+\\frac{x^2}{2!}+\\frac{x^3}{3!}+\\cdots$$ $$\\sin x=x-\\frac{x^3}{3!}+\\frac{x^5}{5!}-\\cdots,\\quad\\cos x=1-\\frac{x^2}{2!}+\\frac{x^4}{4!}-\\cdots$$ $$\\ln(1+x)=x-\\frac{x^2}{2}+\\frac{x^3}{3}-\\cdots,\\quad(1+x)^\\alpha=1+\\alpha x+\\frac{\\alpha(\\alpha-1)}{2!}x^2+\\cdots$$ 特别地 $\\frac{1}{1-x}=1+x+x^2+\\cdots$。",
        "formula": "$$e^x,\\;\\sin x,\\;\\cos x,\\;\\ln(1+x),\\;(1+x)^\\alpha\\text{ 在 }x=0\\text{ 处的标准展开}$$",
        "example": "求 $\\lim_{x\\to0}\\frac{x-\\sin x}{x^3}$。用 $\\sin x=x-\\frac{x^3}{6}+o(x^3)$ 代入：分子 $=\\frac{x^3}{6}+o(x^3)$，故极限为 $\\frac16$。用展开到三阶即可精确出结果，比两次洛必达更直接。",
        "error": "常见错误：①阶数取错——分子各项相减后低阶项相消时，展开阶数必须足够高（保留到分母同阶）；②$\\ln(1+x)$ 的展开只在 $x>-1$ 且收敛半径内有效；③正负号记错（$\\cos x$ 展开从 $1$ 开始、$\\sin x$ 从 $x$ 开始）；④忽略皮亚诺余项 $o(x^n)$ 的书写导致“恒等式”不严谨。",
    },
    "differential-approximation": {
        "intuition": "在一点附近用切线代替曲线：自变量改动 $\\Delta x$ 时，函数改动量 $\\Delta y$ 的主要部分是“斜率乘增量”，即微分 $dy=f'(x_0)\\,dx$；误差是比 $\\Delta x$ 更高阶的小量。",
        "definition": "设 $f$ 在 $x_0$ 处可导，则 $$\\Delta y=f'(x_0)\\Delta x+o(\\Delta x)$$ 线性主部 $dy=f'(x_0)dx$ 称为微分。近似计算公式 $$f(x_0+\\Delta x)\\approx f(x_0)+f'(x_0)\\Delta x$$ 误差估计：若 $|f''|\\le M$，则 $|\\Delta y-dy|\\le\\frac{M}{2}(\\Delta x)^2$。",
        "formula": "$$f(x_0+\\Delta x)\\approx f(x_0)+f'(x_0)\\Delta x$$",
        "example": "近似计算 $\\sqrt{4.02}$。取 $f(x)=\\sqrt x$、$x_0=4$、$\\Delta x=0.02$：$f'(4)=\\frac14$，故 $\\sqrt{4.02}\\approx2+\\frac14\\times0.02=2.005$。真值 $2.00499\\ldots$，误差远小于 $10^{-4}$ 量级的上界估计。",
        "error": "常见错误：①$\\Delta x$ 为负时代入公式忘记符号；②对大增量使用线性近似导致误差失控——微分近似只适用于 $|\\Delta x|$ 很小的场合；③误差估计时不检验 $f''$ 的上界是否存在；④把微分 $dy$（线性主部）与增量 $\\Delta y$（真实改变量）混同。",
    },
    "root-approximation": {
        "intuition": "求方程近似根的两条路：二分法不断把含根区间对半收缩，稳妥但慢；牛顿切线法用切线与 $x$ 轴的交点逼近根，快但要求初值选得好。",
        "definition": "①二分法：设 $f$ 在 $[a,b]$ 上连续且 $f(a)f(b)<0$，由介值定理区间内有根；每步取中点判断符号，保留含根的一半，$n$ 步后误差不超过 $\\frac{b-a}{2^n}$。②牛顿切线法：$$x_{n+1}=x_n-\\frac{f(x_n)}{f'(x_n)}$$ 在根附近 $f'\\ne0$、$f''$ 不变号且初值满足 $f(x_0)f''(x_0)>0$ 时平方收敛。",
        "formula": "$$x_{n+1}=x_n-\\frac{f(x_n)}{f'(x_n)},\\quad |x_n-x^*|\\le\\frac{b-a}{2^n}\\text{（二分法）}$$",
        "example": "用牛顿法求 $\\sqrt2$，即解 $f(x)=x^2-2=0$，迭代式 $x_{n+1}=\\frac12\\left(x_n+\\frac{2}{x_n}\\right)$。取 $x_0=1.5$：$x_1=\\frac12(1.5+1.3333)=1.4167$，$x_2=1.41422$，三步即达 $10^{-5}$ 精度，远快于二分法。",
        "error": "常见错误：①牛顿法初值选在 $f'$ 接近零处导致迭代发散或跳出根的邻域；②不验证 $f(a)f(b)<0$ 就开始二分；③把收敛速度与精度要求混淆——二分 $n$ 次误差上界是 $\\frac{b-a}{2^n}$，需据此规划步数；④遇到重根时牛顿法退化为线性收敛而未察觉。",
    },
    "indefinite-properties": {
        "intuition": "求导的线性性反过来说：和的积分等于积分的和，常数因子可以提到积分号外。这两条性质让复杂被积函数可以拆成“查表可积”的简单块。",
        "definition": "设 $f$、$g$ 的原函数存在，$k$ 为常数，则 $$\\int\\left[f(x)\\pm g(x)\\right]dx=\\int f(x)dx\\pm\\int g(x)dx$$ $$\\int kf(x)dx=k\\int f(x)dx$$ 性质在“整体函数族”意义下成立：两个不定积分相等指原函数族相同，因此分项积分后只需写一个任意常数 $C$。",
        "formula": "$$\\int\\left[f(x)\\pm g(x)\\right]dx=\\int f(x)dx\\pm\\int g(x)dx,\\quad\\int kf(x)dx=k\\int f(x)dx$$",
        "example": "$\\int\\left(3x^2-\\frac{2}{x}\\right)dx=3\\int x^2dx-2\\int\\frac{dx}{x}=x^3-2\\ln|x|+C$。逐项积分后合并写一个 $C$ 即可；对 $\\frac1x$ 的积分保留绝对值以覆盖负半轴。",
        "error": "常见错误：①分项积分后每项各写一个 $C$（多余但不算错，规范上只留一个）；②常数因子漏提或提错符号；③对乘积或商直接套用线性性——$\\int fg\\,dx\\ne\\int f\\,dx\\cdot\\int g\\,dx$，乘积需要分部或换元。",
    },
    "basic-integral-table": {
        "intuition": "把常用导数公式“倒着背”就得到基本积分表：幂函数、指数、对数、三角与反三角的原函数各就各位，是一切积分方法最终要抵达的终点。",
        "definition": "基本积分表（$C$ 为任意常数）：$$\\int x^\\alpha dx=\\frac{x^{\\alpha+1}}{\\alpha+1}+C\\;(\\alpha\\ne-1),\\quad\\int\\frac{dx}{x}=\\ln|x|+C$$ $$\\int e^xdx=e^x+C,\\quad\\int a^xdx=\\frac{a^x}{\\ln a}+C\\;(a>0,\\,a\\ne1)$$ $$\\int\\sin x\\,dx=-\\cos x+C,\\quad\\int\\cos x\\,dx=\\sin x+C$$ $$\\int\\sec^2x\\,dx=\\tan x+C,\\quad\\int\\csc^2x\\,dx=-\\cot x+C$$ $$\\int\\frac{dx}{1+x^2}=\\arctan x+C,\\quad\\int\\frac{dx}{\\sqrt{1-x^2}}=\\arcsin x+C$$",
        "formula": "$$\\int x^\\alpha dx=\\frac{x^{\\alpha+1}}{\\alpha+1}+C,\\quad\\int\\frac{dx}{x}=\\ln|x|+C,\\quad\\int\\frac{dx}{1+x^2}=\\arctan x+C$$",
        "example": "$\\int\\left(\\sqrt{x}+\\frac{1}{\\cos^2x}\\right)dx=\\int x^{1/2}dx+\\int\\sec^2x\\,dx=\\frac{2}{3}x^{3/2}+\\tan x+C$。根式先化为分数指数幂、$\\frac{1}{\\cos^2x}$ 认作 $\\sec^2x$，两者都能直接查表。",
        "error": "常见错误：①$\\alpha=-1$ 时误用幂函数公式（应为 $\\ln|x|+C$）；②三角函数的符号记错（$\\sin$ 的积分带负号、$\\csc^2$ 的积分也带负号）；③$\\ln|x|$ 丢绝对值；④把表扩展时忘记验证——每条公式都可通过“对右边求导还原被积函数”自检。",
    },
    "direct-integration": {
        "intuition": "很多“看起来不会积”的函数，经过代数恒等变形（展开、拆项、三角化简、配根号）后就是积分表的线性组合。先化简后查表，是积分的第一反应。",
        "definition": "直接积分法指不经换元或分部，仅利用恒等变形与线性性质把被积函数化为基本积分表组合的方法。常用变形：多项式展开；分式裂项 $\\frac{1}{x(x+1)}=\\frac1x-\\frac{1}{x+1}$；三角恒等式 $\\sin^2x=\\frac{1-\\cos2x}{2}$、$\\tan^2x=\\sec^2x-1$；根式化为分数指数幂。",
        "formula": "$$\\sin^2x=\\frac{1-\\cos2x}{2},\\quad\\cos^2x=\\frac{1+\\cos2x}{2},\\quad\\tan^2x=\\sec^2x-1$$",
        "example": "$\\int\\frac{x^2}{1+x^2}dx=\\int\\frac{(1+x^2)-1}{1+x^2}dx=\\int\\left(1-\\frac{1}{1+x^2}\\right)dx=x-\\arctan x+C$。分子加一项再减一项的“凑形”是最常用的拆分技巧。",
        "error": "常见错误：①不化简就断言“不可积”，直接放弃；②三角化简时倍角公式符号出错；③裂项后漏项或系数错误——裂项后建议通分回代验证；④忘记加 $C$。",
    },
    "substitution-second-kind": {
        "intuition": "当根号或平方和“堵住”积分去路时，主动引入新变量把根号拆掉：$\\sqrt{a^2-x^2}$ 型令 $x=a\\sin t$，$\\sqrt{a^2+x^2}$ 型令 $x=a\\tan t$，$\\sqrt{x^2-a^2}$ 型令 $x=a\\sec t$，分别化入三角恒等式。",
        "definition": "第二类换元法设 $x=\\varphi(t)$ 可导且有反函数，则 $$\\int f(x)dx=\\left[\\int f\\left(\\varphi(t)\\right)\\varphi'(t)dt\\right]_{t=\\varphi^{-1}(x)}$$ 三角代换的三种标准型：①含 $\\sqrt{a^2-x^2}$ 令 $x=a\\sin t$；②含 $\\sqrt{a^2+x^2}$ 令 $x=a\\tan t$；③含 $\\sqrt{x^2-a^2}$ 令 $x=a\\sec t$。简单无理式也可令整个根式为新变量（如 $t=\\sqrt{x}$）。积分完成后必须回代为 $x$ 的函数，常借助辅助直角三角形。",
        "formula": "$$\\sqrt{a^2-x^2}\\xrightarrow{x=a\\sin t}a\\cos t,\\quad\\sqrt{a^2+x^2}\\xrightarrow{x=a\\tan t}a\\sec t,\\quad\\sqrt{x^2-a^2}\\xrightarrow{x=a\\sec t}a\\tan t$$",
        "example": "$\\int\\sqrt{a^2-x^2}dx$（$a>0$）。令 $x=a\\sin t$，$dx=a\\cos t\\,dt$，积分化为 $a^2\\int\\cos^2t\\,dt=\\frac{a^2}{2}\\left(t+\\sin t\\cos t\\right)+C$；回代 $t=\\arcsin\\frac{x}{a}$、$\\sin t\\cos t=\\frac{x}{a}\\cdot\\frac{\\sqrt{a^2-x^2}}{a}$，得 $\\frac{a^2}{2}\\arcsin\\frac{x}{a}+\\frac{x}{2}\\sqrt{a^2-x^2}+C$。",
        "error": "常见错误：①代换后忘记乘 $dx=\\varphi'(t)dt$；②积分完成后不回代，结果仍含 $t$；③三角代换的类型与根式形态不匹配（三种标准型不能混用）；④开根号时丢绝对值导致符号错误——在限定 $t$ 的范围（如 $t\\in\\left[-\\frac\\pi2,\\frac\\pi2\\right]$）内确定符号。",
    },
    "rational-integration": {
        "intuition": "有理函数是“最听话”的被积函数：任何真分式都能唯一分解为部分分式（简单分式之和），而每类部分分式的积分都有固定算法，最终只落到多项式、对数与反正切。",
        "definition": "①假分式先化为“多项式+真分式”；②真分式按分母因式分解写部分分式：分母含因子 $(x-a)^k$ 则设 $\\frac{A_1}{x-a}+\\cdots+\\frac{A_k}{(x-a)^k}$，含不可约二次因子 $(x^2+px+q)^m$ 则设 $\\frac{B_1x+C_1}{x^2+px+q}+\\cdots$；③待定系数（赋值法或比较同次幂系数）；④逐项积分：$\\int\\frac{dx}{(x-a)^k}$ 在 $k=1$ 时为对数、$k>1$ 时为幂函数型；二次项配方后化为 $\\arctan$ 与对数的组合。",
        "formula": "$$\\int\\frac{dx}{x-a}=\\ln|x-a|+C,\\quad\\int\\frac{dx}{(x-a)^k}=\\frac{(x-a)^{1-k}}{1-k}+C\\;(k\\ne1)$$",
        "example": "$\\int\\frac{x+3}{x^2-5x+6}dx$。分母 $=(x-2)(x-3)$，设 $\\frac{x+3}{(x-2)(x-3)}=\\frac{A}{x-2}+\\frac{B}{x-3}$，解得 $A=-5$、$B=6$。积分 $=-5\\ln|x-2|+6\\ln|x-3|+C$。待定系数用赋值法最快：令 $x=2$、$x=3$ 分别立得 $A$、$B$。",
        "error": "常见错误：①假分式（分子次数不低于分母）未先做除法就直接设部分分式；②不可约二次因子误分解为两个一次复因子（初等积分应保持二次整体）；③部分分式的分子设为常数——对应二次因子的分子应是一次式 $Bx+C$；④漏 $\\ln$ 的绝对值。",
    },
    "trigonometric-integration": {
        "intuition": "三角有理式的积分按“奇偶”走捷径：正弦或余弦为奇次幂时拆一个出来凑微分；都是偶次幂时用倍角公式降幂；万能公式 $t=\\tan\\frac{x}{2}$ 兜底，一定能化为有理函数积分。",
        "definition": "记 $t=\\tan\\frac{x}{2}$，则 $\\sin x=\\frac{2t}{1+t^2}$、$\\cos x=\\frac{1-t^2}{1+t^2}$、$dx=\\frac{2\\,dt}{1+t^2}$，任何 $\\int R(\\sin x,\\cos x)dx$ 都化为有理函数积分。但万能代换往往繁琐，优先尝试：①$R(-\\sin x,\\cos x)=-R(\\sin x,\\cos x)$ 时令 $t=\\cos x$；②$R(\\sin x,-\\cos x)=-R$ 时令 $t=\\sin x$；③$R(-\\sin x,-\\cos x)=R$ 时令 $t=\\tan x$。",
        "formula": "$$\\sin x=\\frac{2t}{1+t^2},\\;\\cos x=\\frac{1-t^2}{1+t^2},\\;dx=\\frac{2dt}{1+t^2}\\quad\\left(t=\\tan\\frac{x}{2}\\right)$$",
        "example": "$\\int\\sin^2x\\cos^3x\\,dx$。$\\cos x$ 为奇次幂，拆出一个：$\\int\\sin^2x\\left(1-\\sin^2x\\right)\\cos x\\,dx$，令 $t=\\sin x$ 得 $\\int\\left(t^2-t^4\\right)dt=\\frac{\\sin^3x}{3}-\\frac{\\sin^5x}{5}+C$，远快于万能代换。",
        "error": "常见错误：①一律用万能代换导致高次有理分式、计算失控——先检查奇偶性选简捷代换；②半角代换后忘记 $dx=\\frac{2dt}{1+t^2}$；③降幂公式 $\\sin^2x=\\frac{1-\\cos2x}{2}$ 记错符号；④积出结果不化简、不验证（对结果求导应还原被积函数）。",
    },
    "radical-integration": {
        "intuition": "简单无理式积分的思路是“整体换元去根号”：令根式本身（或根号内的线性式）为新变量，把无理函数化为有理函数再处理。",
        "definition": "形如 $\\int R\\left(x,\\sqrt[n]{\\frac{ax+b}{cx+d}}\\right)dx$ 的积分，令 $t=\\sqrt[n]{\\frac{ax+b}{cx+d}}$ 解出 $x$ 即可化为 $t$ 的有理函数积分。对 $\\sqrt{ax+b}$ 型令 $t=\\sqrt{ax+b}$（即 $x=\\frac{t^2-b}{a}$）；含 $\\sqrt[n]{x}$ 与 $\\sqrt[m]{x}$ 时令 $t=\\sqrt[\\mathrm{lcm}(n,m)]{x}$ 一次消去所有根号。",
        "formula": "$$t=\\sqrt[n]{\\frac{ax+b}{cx+d}}\\;\\Longrightarrow\\;x=\\frac{dt^n-b}{a-ct^n}\\;\\Longrightarrow\\;\\text{有理函数积分}$$",
        "example": "$\\int\\frac{dx}{1+\\sqrt{x}}$。令 $t=\\sqrt x$，$x=t^2$、$dx=2t\\,dt$，积分化为 $\\int\\frac{2t}{1+t}dt=2\\int\\left(1-\\frac{1}{1+t}\\right)dt=2t-2\\ln(1+t)+C=2\\sqrt x-2\\ln\\left(1+\\sqrt x\\right)+C$。",
        "error": "常见错误：①换元后 $dx$ 没有跟着变换（漏乘 $2t$ 之类的因子）；②多个不同次根式只消去其中一个；③回代不完全，结果里残留 $t$；④去根号时忽视定义域（被开方数非负）导致常数符号错误。",
    },
    "integration-strategy": {
        "intuition": "拿到一个积分，按固定顺序“过筛子”：先看能否恒等变形直接查表，再看是否具备 $f(g(x))g'(x)$ 的凑微分结构，其次考虑分部与三角/根式代换，最后退回部分分式或万能代换。",
        "definition": "方法选择的经验顺序：①化简（拆项、恒等变形）后直接积分；②第一类换元（凑微分）：被积函数呈复合结构与内层导数之积；③分部积分：两类不同函数的乘积（反对幂三指定 $u$）；④第二类换元：含根式 $\\sqrt{a^2\\pm x^2}$、$\\sqrt{x^2-a^2}$ 或 $\\sqrt[n]{\\frac{ax+b}{cx+d}}$；⑤有理函数部分分式；⑥三角有理式先试奇偶代换、后用万能代换。同一题目常需多种方法接力。",
        "formula": "$$\\text{化简}\\to\\text{凑微分}\\to\\text{分部}\\to\\text{代换}\\to\\text{部分分式/万能代换}$$",
        "example": "$\\int x\\,e^{x^2}dx$ 走凑微分：$=\\frac12\\int e^{x^2}d\\left(x^2\\right)=\\frac12e^{x^2}+C$；而 $\\int x^2e^{x}dx$ 凑不成 $u=x^2$ 的复合结构，走分部（两次），得 $e^x\\left(x^2-2x+2\\right)+C$。结构差一点，方法完全不同——这正是需要策略的原因。",
        "error": "常见错误：①不观察结构就硬套单一方法，越做越复杂；②分部积分选错 $u$ 导致循环；③忘记“先化简”这一步，把本可直接查表的积分复杂化；④两种方法接力时中间结果抄写出错——每步都应对中间式求导抽查。",
    },
    "indefinite-integral-review": {
        "intuition": "综合积分题考验的是“识别+组合”：一道题往往先用代数或三角变形打开缺口，再接换元或分部，最后落回积分表。练综合题的目标是把方法选择变成条件反射。",
        "definition": "综合题的应对框架：①通读结构，标记“根式、三角、多项式、分式”四类元件；②判断主导难点（根式→去根号；分式→裂项；乘积→分部；复合→换元）；③执行第一步化简后重新审视——剩余部分可能需要第二种方法；④全程保留任意常数，最终结果对 $x$ 求导自检。",
        "formula": "$$\\text{变形}\\to\\text{换元/分部}\\to\\text{查表}\\to\\text{求导验证}$$",
        "example": "$\\int e^{\\sqrt{x}}dx$。先换元去根号：$t=\\sqrt x$、$dx=2t\\,dt$，化为 $2\\int te^t dt$；再分部：$2\\left(te^t-e^t\\right)+C$；回代得 $2e^{\\sqrt{x}}\\left(\\sqrt x-1\\right)+C$。一道题串起第二类换元与分部两个方法。",
        "error": "常见错误：①方法选择僵化，一条路走到黑不回头；②多次变换后忘记逐层回代；③不做最终验证——综合题中间步骤多，求导自检是最有效的防错手段；④任意常数在分部过程中被吞掉。",
    },
    "riemann-sum": {
        "intuition": "测量曲边下的面积时，先把底边切成许多小段，每段上方用细长矩形代替曲边梯形；所有矩形面积相加得到黎曼和。切得越细，矩形之和越贴近真实面积。",
        "definition": "设 $f$ 在 $[a,b]$ 上有界。取分割 $a=x_0<x_1<\\cdots<x_n=b$，每段长度 $\\Delta x_i=x_i-x_{i-1}$，任取样本点 $\\xi_i\\in[x_{i-1},x_i]$，称 $$S_n=\\sum_{i=1}^{n}f\\left(\\xi_i\\right)\\Delta x_i$$ 为黎曼和。若记 $\\lambda=\\max\\Delta x_i$，当 $\\lambda\\to0$ 时 $S_n$ 趋于同一极限（与分割及样本点取法无关），这个极限就是定积分。等分分割下 $\\lambda=\\frac{b-a}{n}\\to0$ 等价于 $n\\to\\infty$。",
        "formula": "$$S_n=\\sum_{i=1}^{n}f\\left(\\xi_i\\right)\\Delta x_i\\;\\xrightarrow{\\lambda\\to0}\\;\\int_a^bf(x)dx$$",
        "example": "用黎曼和求 $\\int_0^1x^2dx$：等分分割，取 $\\xi_i=\\frac{i}{n}$，则 $S_n=\\sum_{i=1}^n\\frac{i^2}{n^2}\\cdot\\frac1n=\\frac{n(n+1)(2n+1)}{6n^3}$，令 $n\\to\\infty$ 得 $\\frac13$。样本点取右端点只是其中一种取法，极限结果与取法无关。",
        "error": "常见错误：①把 $\\lambda\\to0$ 与 $n\\to\\infty$ 无条件等同——只有等分（或最长段确实趋于零）时才等价；②求和公式用错（$\\sum i^2=\\frac{n(n+1)(2n+1)}{6}$ 而不是 $\\left(\\frac{n(n+1)}{2}\\right)^2$）；③黎曼和的极限若依赖样本点取法，说明不可积，不能硬取极限。",
    },
    "definite-integral-properties": {
        "intuition": "定积分的基本性质都符合“面积直觉”：整体面积等于各段面积之和；较高的函数围成较大面积；用最小值乘长度与最大值乘长度可以夹住积分值。",
        "definition": "设 $f$、$g$ 在 $[a,b]$ 上可积：①线性性 $\\int_a^b\\left(\\alpha f+\\beta g\\right)dx=\\alpha\\int_a^bfdx+\\beta\\int_a^bg\\,dx$；②区间可加性 $\\int_a^bfdx=\\int_a^cfdx+\\int_c^bfdx$（$c$ 可在区间外，配合反号规则理解）；③反序规则 $\\int_b^afdx=-\\int_a^bfdx$、$\\int_a^afdx=0$；④保号性：若 $f\\le g$ 则 $\\int_a^bfdx\\le\\int_a^bg\\,dx$；⑤估值定理：$m(b-a)\\le\\int_a^bfdx\\le M(b-a)$，其中 $m、M$ 为 $f$ 在区间上的最小、最大值。",
        "formula": "$$m(b-a)\\le\\int_a^bf(x)dx\\le M(b-a)$$",
        "example": "估计 $\\int_0^2\\frac{x}{1+x^2}dx$ 的范围。$f'(x)=\\frac{1-x^2}{(1+x^2)^2}$，在 $[0,2]$ 上最大值 $f(1)=\\frac12$、最小值 $f(2)=\\frac25$，故 $\\frac45\\le\\int_0^2fdx\\le1$。不等式估值在不需要精确值时非常高效。",
        "error": "常见错误：①积分不等式两边同乘负数时忘记反号；②区间可加性用于 $c\\notin[a,b]$ 时不调整方向；③把保号性当成充要条件——$f>0$ 可推出积分为正，但积分为正时函数在区间内仍可能局部取负值；④估值时 $m、M$ 求错（忘记检查驻点与端点）。",
    },
    "integral-mean-value": {
        "intuition": "曲边梯形的面积可以摊平成同底等高的矩形：存在一个高度 $f(\\xi)$，使矩形面积 $f(\\xi)(b-a)$ 恰好等于积分值。这个等效高度就是函数在区间上的“积分平均值”。",
        "definition": "设 $f$ 在 $[a,b]$ 上连续，则存在 $\\xi\\in[a,b]$ 使得 $$\\int_a^bf(x)dx=f\\left(\\xi\\right)(b-a)$$ 等价形式 $f(\\xi)=\\frac{1}{b-a}\\int_a^bf(x)dx$ 称为 $f$ 的积分平均值。证明思路：由最值定理与估值定理夹逼，再用闭区间上连续函数的介值定理。注意与微分中值定理的区别：这里的 $\\xi$ 来自函数值域的介值性。",
        "formula": "$$\\int_a^bf(x)dx=f\\left(\\xi\\right)(b-a),\\quad\\xi\\in[a,b]$$",
        "example": "$\\int_0^\\pi\\sin x\\,dx=2$，区间长度 $\\pi$，故存在 $\\xi$ 使 $\\sin\\xi=\\frac{2}{\\pi}\\approx0.637$，如 $\\xi=\\arcsin\\frac2\\pi\\approx0.69\\in[0,\\pi]$。平均值也可直接用于估算：该区间上正弦的平均高度就是 $\\frac2\\pi$。",
        "error": "常见错误：①把 $\\xi$ 的范围写成开区间 $(a,b)$ 时未验证——闭区间连续即可保证 $\\xi\\in[a,b]$，加强到开区间需要额外条件；②与拉格朗日中值定理的 $\\xi$ 混淆（一个来自介值定理、一个来自导数）；③被积函数不连续（如有跳跃间断）时滥用定理。",
    },
    "definite-substitution": {
        "intuition": "定积分换元与不定积分同源，但纪律更严：换元必须同时换积分限，得到的新积分直接算数，不需要回代。这省去了回代与开根号讨论的麻烦。",
        "definition": "设 $f$ 在 $[a,b]$ 上连续，$x=\\varphi(t)$ 在 $[\\alpha,\\beta]$ 上有连续导数，且当 $t$ 从 $\\alpha$ 变到 $\\beta$ 时 $\\varphi(t)$ 从 $a$ 单调变到 $b$，则 $$\\int_a^bf(x)dx=\\int_\\alpha^\\beta f\\left(\\varphi(t)\\right)\\varphi'(t)dt$$ 其中 $a=\\varphi(\\alpha)$、$b=\\varphi(\\beta)$。原变量上下限换成新变量的对应值，之后按新积分直接计算。",
        "formula": "$$\\int_a^bf(x)dx\\;\\xrightarrow{x=\\varphi(t)}\\;\\int_\\alpha^\\beta f\\left(\\varphi(t)\\right)\\varphi'(t)dt$$",
        "example": "$\\int_0^4\\frac{dx}{1+\\sqrt{x}}$。令 $t=\\sqrt x$，即 $x=t^2$；$x=0\\Rightarrow t=0$，$x=4\\Rightarrow t=2$：$\\int_0^2\\frac{2t\\,dt}{1+t}=2\\left[t-\\ln(1+t)\\right]_0^2=4-2\\ln3$。全程不再出现 $x$，也没有回代步骤。",
        "error": "常见错误：①换元不换限（或忘了把新上限对应旧上限），是最常见的定积分错误；②新积分限的顺序颠倒——$\\varphi$ 不必单调递增，允许上限对应更小的 $t$，但必须对应正确；③代换函数在区间上不单调或有不可导点时照用；④奇偶对称化简时区间不是关于原点对称却硬用对称性。",
    },
    "definite-parts": {
        "intuition": "把不定分部积分公式“带上上下限”：乘积项在端点取值之差减去剩余积分，每一步都在数值层面进行，符号与边界值一目了然。",
        "definition": "设 $u(x)$、$v(x)$ 在 $[a,b]$ 上有连续导数，则 $$\\int_a^bu\\,dv=\\Big[uv\\Big]_a^b-\\int_a^bv\\,du$$ 其中 $\\Big[uv\\Big]_a^b=uv\\big|_{x=b}-uv\\big|_{x=a}$。$u$、$dv$ 的选择原则与不定积分相同（反对幂三指），但边界项立即代入数值，可及时发现符号错误。",
        "formula": "$$\\int_a^bu\\,dv=\\Big[uv\\Big]_a^b-\\int_a^bv\\,du$$",
        "example": "$\\int_0^{\\frac{\\pi}{2}}x\\cos x\\,dx$。取 $u=x$、$dv=\\cos x\\,dx$，则 $\\Big[x\\sin x\\Big]_0^{\\pi/2}-\\int_0^{\\pi/2}\\sin x\\,dx=\\frac{\\pi}{2}-\\Big[-\\cos x\\Big]_0^{\\pi/2}=\\frac{\\pi}{2}-1$。边界项 $\\frac{\\pi}{2}$ 立刻算出，只留下一个更简单的积分。",
        "error": "常见错误：①边界项只代一端或符号弄反；②第二次分部时换了 $u$ 的类型导致绕回原积分（递推 $\\int_0^{\\pi/2}\\sin^nx\\,dx$ 类问题尤其注意保持同一选择）；③把 $\\Big[uv\\Big]_a^b$ 写成 $uv+C$；④被积函数在区间端点无界时滥用公式（应转反常积分）。",
    },
    "symmetry-periodicity-integrals": {
        "intuition": "对称与周期能大幅省算：奇函数在对称区间上“正负面积相抵”积分为零；偶函数只算一半再翻倍；周期函数在每个整周期上的积分相同，长区间可折叠成短区间。",
        "definition": "①奇偶性：若 $f$ 为奇函数，则 $\\int_{-a}^{a}f(x)dx=0$；若 $f$ 为偶函数，则 $\\int_{-a}^{a}f(x)dx=2\\int_0^{a}f(x)dx$（要求 $f$ 在 $[-a,a]$ 上可积）。②周期性：设 $f$ 以 $T$ 为周期且在一个周期上可积，则对任意 $a$，$\\int_a^{a+T}f(x)dx=\\int_0^{T}f(x)dx$；长为 $nT$ 的区间积分等于 $n$ 倍单周期积分。",
        "formula": "$$\\int_{-a}^{a}f=0\\;(\\text{奇}),\\quad\\int_{-a}^{a}f=2\\int_0^{a}f\\;(\\text{偶}),\\quad\\int_a^{a+T}f=\\int_0^{T}f\\;(\\text{周期 }T)$$",
        "example": "$\\int_{-1}^{1}\\frac{x^3\\cos x}{1+x^2}dx$：被积函数是“奇×偶÷偶”结构，关于 $x$ 为奇函数，对称区间上积分立即得 $0$，无需任何计算。再如 $\\int_0^{4\\pi}\\left|\\sin x\\right|dx$：$\\left|\\sin x\\right|$ 以 $\\pi$ 为周期，积分为 $4\\times\\int_0^{\\pi}\\sin x\\,dx=8$。",
        "error": "常见错误：①区间不关于原点对称却套奇偶结论；②奇偶判断失误——“奇乘奇为偶、奇乘偶为奇”的复合规则记反；③周期平移规则记错起点：$\\int_a^{a+T}$ 与起点 $a$ 无关，但 $\\int_0^{2T}$ 是 $2\\int_0^T$ 而 $\\int_0^{1.5T}$ 不能这样折；④被积函数无界时（反常积分）奇偶性需谨慎使用，先确认收敛。",
    },
    "improper-infinite-interval": {
        "intuition": "把无穷区间截断成有限区间算面积，再让截断点奔向无穷：若面积的极限存在，就说反常积分收敛；面积随截断无限增长则发散。",
        "definition": "设 $f$ 在 $x\\ge a$ 上连续，定义 $$\\int_a^{+\\infty}f(x)dx=\\lim_{t\\to+\\infty}\\int_a^{t}f(x)dx$$ 若极限存在称积分收敛，否则发散。类似定义 $\\int_{-\\infty}^{b}$ 与 $\\int_{-\\infty}^{+\\infty}$；后者定义为 $\\int_{-\\infty}^{c}+\\int_{c}^{+\\infty}$，两段都收敛才收敛。计算仍用牛顿-莱布尼茨公式：$\\int_a^{+\\infty}f=\\Big[F(x)\\Big]_a^{+\\infty}=\\lim_{x\\to+\\infty}F(x)-F(a)$。",
        "formula": "$$\\int_a^{+\\infty}f(x)dx=\\lim_{t\\to+\\infty}\\Big[F(t)-F(a)\\Big]$$",
        "example": "$\\int_1^{+\\infty}\\frac{dx}{x^2}=\\lim_{t\\to+\\infty}\\left[-\\frac1x\\right]_1^{t}=\\lim_{t\\to+\\infty}\\left(1-\\frac1t\\right)=1$，收敛。而 $\\int_1^{+\\infty}\\frac{dx}{x}=\\lim_{t\\to+\\infty}\\ln t=+\\infty$，发散——同为“倒数”，平方与否决定收敛。",
        "error": "常见错误：①不取极限直接把 $+\\infty$ 代入原函数；②$\\int_{-\\infty}^{+\\infty}$ 不拆成两段分别判断（整体取对称极限 $\\lim_{t\\to\\infty}\\int_{-t}^{t}$ 的“柯西主值”收敛不代表反常积分收敛）；③把发散误当“积分不存在可用于恒等变形”；④收敛性讨论与被积函数符号有关，混用绝对收敛与条件收敛。",
    },
    "improper-unbounded-function": {
        "intuition": "函数在区间内某点“冲向无穷”（瑕点）时，把瑕点挖掉一小段，先算剩余面积，再让挖掉的部分收缩到零：极限存在则收敛。几何上是对无穷尖峰“削顶逼近”。",
        "definition": "设 $f$ 在 $a<x\\le b$ 上连续且 $\\lim_{x\\to a^+}f(x)=\\infty$（$a$ 为瑕点），定义 $$\\int_a^{b}f(x)dx=\\lim_{\\varepsilon\\to0^+}\\int_{a+\\varepsilon}^{b}f(x)dx$$ 若极限存在称收敛。瑕点在上限时类似定义；区间内部有瑕点 $c\\in(a,b)$ 时必须拆成 $\\int_a^c$ 与 $\\int_c^b$ 两段，两段都收敛才收敛。",
        "formula": "$$\\int_a^{b}f(x)dx=\\lim_{\\varepsilon\\to0^+}\\int_{a+\\varepsilon}^{b}f(x)dx\\quad\\left(\\text{瑕点 }a\\right)$$",
        "example": "$\\int_0^1\\frac{dx}{\\sqrt{x}}$：$x=0$ 是瑕点。$\\lim_{\\varepsilon\\to0^+}\\int_\\varepsilon^1x^{-1/2}dx=\\lim_{\\varepsilon\\to0^+}\\left(2-2\\sqrt{\\varepsilon}\\right)=2$，收敛。而 $\\int_0^1\\frac{dx}{x}=\\lim_{\\varepsilon\\to0^+}\\left(-\\ln\\varepsilon\\right)=+\\infty$，发散。尖峰不够“尖”时面积有限。",
        "error": "常见错误：①看不出瑕点，直接用牛顿-莱布尼茨公式算出有限值（如 $\\int_{-1}^{1}\\frac{dx}{x^2}$ 直接代值得 $-2$，负值显然荒谬，正确结论是发散）；②内部瑕点不拆两段，用跨瑕点的原函数值相减；③$\\varepsilon$ 从两侧同时趋近（应单侧）；④与无穷区间混合型积分（既有瑕点又无界）漏判其一。",
    },
    "improper-convergence": {
        "intuition": "$p$ 积分给出收敛的分水岭：$\\int_1^{+\\infty}\\frac{dx}{x^p}$ 在 $p>1$ 时收敛（尾巴衰减够快），$p\\le1$ 发散；$\\int_0^1\\frac{dx}{x^p}$ 恰好相反，$p<1$ 收敛。以此为标尺可比较判断更复杂的反常积分。",
        "definition": "①无穷区间 $p$ 积分：$\\int_1^{+\\infty}\\frac{dx}{x^p}$ 当 $p>1$ 收敛（值为 $\\frac{1}{p-1}$），当 $p\\le1$ 发散。②瑕积分 $p$ 积分：$\\int_0^1\\frac{dx}{x^p}$ 当 $p<1$ 收敛（值为 $\\frac{1}{1-p}$），当 $p\\ge1$ 发散。比较判别法：若 $0\\le f\\le g$ 且 $\\int g$ 收敛则 $\\int f$ 收敛；$\\int f$ 发散则 $\\int g$ 发散。极限形式：若 $\\lim_{x\\to\\infty}\\frac{f(x)}{1/x^p}=\\lambda>0$，则 $f$ 与 $\\frac{1}{x^p}$ 同敛散。",
        "formula": "$$\\int_1^{+\\infty}\\frac{dx}{x^p}\\text{ 收敛}\\iff p>1;\\quad\\int_0^1\\frac{dx}{x^p}\\text{ 收敛}\\iff p<1$$",
        "example": "判断 $\\int_1^{+\\infty}\\frac{dx}{x\\sqrt{1+x}}$ 的敛散性：$x\\to+\\infty$ 时被积函数 $\\sim\\frac{1}{x^{3/2}}$，与 $\\frac{1}{x^{3/2}}$ 同敛散；因 $p=\\frac32>1$，积分收敛。用等价量（或极限比较法）找主导幂次即可，无需算出积分值。",
        "error": "常见错误：①两类 $p$ 积分的收敛条件记反（无穷区间要 $p>1$，瑕积分要 $p<1$）；②比较判别法用于变号被积函数（应先取绝对值或拆分正负部）；③等价代换时把低阶项当主导（$\\frac{1}{x^2+x}\\sim\\frac1{x^2}$ 而不是 $\\sim\\frac1x$）；④混合型积分只判断其中一种瑕点。",
    },
    "area-parametric-polar": {
        "intuition": "参数方程下面积仍按“上减下乘宽”累加，只是宽度换成 $x'(t)dt$；极坐标下则以扇形微元代替矩形微元，面积是“半乘半径平方乘转角”的累加。",
        "definition": "①参数式：设曲边梯形由参数曲线 $x=x(t)$、$y=y(t)$（$t\\in[\\alpha,\\beta]$，$x(t)$ 单调增）与 $x$ 轴、直线 $x=x(\\alpha)$、$x=x(\\beta)$ 围成，则 $$S=\\int_\\alpha^\\beta y(t)x'(t)dt$$ ②极坐标：由曲线 $r=r(\\theta)$ 与射线 $\\theta=\\alpha$、$\\theta=\\beta$ 围成的曲边扇形面积 $$S=\\frac12\\int_\\alpha^\\beta r^2(\\theta)\\,d\\theta$$ 极坐标面积出现负值（如玫瑰线）时需分段取绝对值。",
        "formula": "$$S=\\left|\\int_\\alpha^\\beta y(t)x'(t)dt\\right|,\\quad S=\\frac12\\int_\\alpha^\\beta r^2(\\theta)d\\theta$$",
        "example": "求心形线 $r=a(1+\\cos\\theta)$（$a>0$）围成的面积。利用对称性取 $\\theta\\in[0,\\pi]$：$S=2\\cdot\\frac12\\int_0^{\\pi}a^2(1+\\cos\\theta)^2d\\theta=a^2\\int_0^{\\pi}\\left(1+2\\cos\\theta+\\cos^2\\theta\\right)d\\theta=a^2\\left(\\pi+0+\\frac{\\pi}{2}\\right)=\\frac{3\\pi a^2}{2}$。",
        "error": "常见错误：①参数式忘记乘 $x'(t)$ 或上下限仍写 $x$ 的值（应写 $t$ 的对应值）；②极坐标面积公式漏乘 $\\frac12$；③玫瑰线 $r=\\sin3\\theta$ 类曲线一瓣的 $\\theta$ 范围求错，导致重复或遗漏；④曲线过极点或自交时分段不当。",
    },
    "volume-slicing": {
        "intuition": "把立体垂直于某轴切成薄片，每片体积≈截面积×厚度；截面面积随位置变化时，体积就是截面函数的定积分——“面积函数的积分是体积”。",
        "definition": "设立体夹在平面 $x=a$ 与 $x=b$ 之间，且与 $x$ 轴垂直的截面面积是连续函数 $A(x)$，则体积 $$V=\\int_a^bA(x)dx$$ 旋转体的圆盘法、垫圈法都是它的特例（截面为圆或圆环）。已知平行截面面积的立体（如楔形体、锥体）都可直接套用。",
        "formula": "$$V=\\int_a^bA(x)dx$$",
        "example": "用平行截面法验证正圆锥体积公式。设底面半径 $R$、高 $h$，取顶点为原点、轴为 $x$ 轴（$0\\le x\\le h$）。距顶点 $x$ 处的截面是圆，由相似三角形得半径 $r(x)=\\frac{R}{h}x$，故 $A(x)=\\pi r^2(x)=\\frac{\\pi R^2}{h^2}x^2$，于是 $V=\\int_0^h\\frac{\\pi R^2}{h^2}x^2dx=\\frac{\\pi R^2}{h^2}\\cdot\\frac{h^3}{3}=\\frac13\\pi R^2h$，与熟知的锥体体积公式一致。关键是先把 $A(x)$ 用相似关系写出。",
        "error": "常见错误：①截面面积函数 $A(x)$ 推导错误（截面的高、宽与立体几何关系没画清楚）；②切片方向选择不当导致 $A(x)$ 表达式复杂——换一个轴切可能立刻简化；③把旋转体截面（圆）面积写成 $\\pi f(x)$ 漏平方；④积分限与切片轴不匹配。",
    },
    "surface-area-revolution": {
        "intuition": "旋转曲面像“无数条细环带”拼成：每条环带的宽是弧微元 $ds=\\sqrt{1+y'^2}dx$ 而不是 $dx$，周长是 $2\\pi|y|$，两者相乘再累加就是侧面积。",
        "definition": "设 $y=f(x)\\ge0$ 在 $[a,b]$ 上有连续导数，曲线绕 $x$ 轴旋转一周所得曲面面积 $$S=2\\pi\\int_a^bf(x)\\sqrt{1+f'^2(x)}\\,dx$$ 绕 $y$ 轴旋转时 $$S=2\\pi\\int_a^b|x|\\sqrt{1+f'^2(x)}\\,dx$$ 参数方程 $x=x(t)$、$y=y(t)$ 下 $S=2\\pi\\int_\\alpha^\\beta|y(t)|\\sqrt{x'^2+y'^2}\\,dt$（绕 $x$ 轴）。",
        "formula": "$$S_{x\\text{轴}}=2\\pi\\int_a^b|y|\\sqrt{1+y'^2}\\,dx$$",
        "example": "验证半径为 $R$ 的球面面积：取上半圆 $y=\\sqrt{R^2-x^2}$（$x\\in[-R,R]$），$y'=-\\frac{x}{y}$，$1+y'^2=\\frac{R^2}{R^2-x^2}$，故 $S=2\\pi\\int_{-R}^{R}\\sqrt{R^2-x^2}\\cdot\\frac{R}{\\sqrt{R^2-x^2}}dx=2\\pi R\\int_{-R}^{R}dx=4\\pi R^2$，与已知公式一致。",
        "error": "常见错误：①被积函数忘记 $\\sqrt{1+y'^2}$（用 $dx$ 代替弧微元 $ds$）——相当于把环带当圆柱；②漏乘 $2\\pi|y|$ 或在 $y<0$ 时丢绝对值；③绕 $y$ 轴时周长误用 $y$（应为 $|x|$）；④与旋转体体积公式混淆（体积平方、侧面积不平方）。",
    },
    "work-by-variable-force": {
        "intuition": "恒力做功等于力乘距离；力随位置变化时，把路程切成小段，每段上近似恒力，做功微元 $dW=F(x)dx$，累加即得变力做功的定积分。",
        "definition": "设物体沿 $x$ 轴从 $a$ 移动到 $b$，受力 $F(x)$ 连续变化，则 $$W=\\int_a^bF(x)dx$$ 典型模型：①弹簧做功 $F=kx$（胡克定律）：$W=\\int_0^{x_0}kx\\,dx=\\frac12kx_0^2$；②抽水做功：把容器中液体抽到高度 $H$，薄层在深度 $x$ 处需提升 $H-x$，$dW=\\rho g\\,A(x)(H-x)dx$，其中 $A(x)$ 为液面截面积。",
        "formula": "$$W=\\int_a^bF(x)dx,\\quad dW=\\rho g\\,A(x)(H-x)dx\\;\\text{（抽水）}$$",
        "example": "半径为 $R$ 的半球形水池盛满水（密度 $\\rho$），将水全部抽到池口平面，求做功。取深度 $x$ 自池口向下，液面截面积 $A(x)=\\pi\\left(R^2-x^2\\right)$，提升高度为 $x$：$W=\\int_0^{R}\\rho g\\pi\\left(R^2-x^2\\right)x\\,dx=\\rho g\\pi\\left[\\frac{R^2x^2}{2}-\\frac{x^4}{4}\\right]_0^{R}=\\frac{\\pi\\rho gR^4}{4}$。",
        "error": "常见错误：①抽水问题中提升高度写成固定值（忽略不同深度水层提升距离不同）；②截面面积函数 $A(x)$ 按错误的截面（水平面 vs 竖直面）计算；③单位不统一（长度单位与密度、$g$ 的配套）；④把变力当恒力用中点的力近似——应积分而不是取平均高度乘总重（除非截面积恒定）。",
    },
    "fluid-force": {
        "intuition": "液体压强随深度线性增加 $p=\\rho gx$，薄板不同深度处压强不同。把薄板水平切成细条，每条上的压力≈压强×条面积，累加即得总压力的定积分。",
        "definition": "设铅直薄板浸入密度为 $\\rho$ 的液体中，深度 $x$ 处薄板的水平宽度为 $w(x)$，薄板占据深度区间 $[a,b]$，则一侧所受静压力 $$F=\\rho g\\int_a^bx\\,w(x)\\,dx$$ 深度从液面算起；若薄板不触及液面，$[a,b]$ 是其最浅与最深深度。矩形、三角形、圆板等规则形状都可先写 $w(x)$ 再积分。",
        "formula": "$$F=\\rho g\\int_a^bx\\,w(x)\\,dx$$",
        "example": "宽 $2\\,\\mathrm{m}$、高 $3\\,\\mathrm{m}$ 的矩形闸门铅直放入水中，上沿与水面齐平。宽度 $w(x)=2$，$F=\\rho g\\int_0^32x\\,dx=\\rho g\\cdot9$。取水的 $\\rho=1000$、$g=9.8$，得 $F=8.82\\times10^4\\,\\mathrm{N}$。压力中心低于几何中心（压强随深度增加），由 $x$ 的一次权重决定。",
        "error": "常见错误：①用平均深度×总面积近似任意形状薄板——只对矩形（宽度恒定）恰好精确，其他形状必须积分；②$w(x)$ 写成竖直边长而不是深度 $x$ 处的水平宽度；③深度参考面选错（应从自由液面算起，与容器形状无关）；④忘记薄板两侧（若双侧受压需说明只算一侧）。",
    },
    "average-value-function": {
        "intuition": "函数的平均值不是端点平均，而是“积分摊平”：把区间上的总面积除以区间长度，得到等效常值高度，它与积分中值定理中的 $f(\\xi)$ 是同一个量。",
        "definition": "设 $f$ 在 $[a,b]$ 上连续，定义平均值 $$\\bar{f}=\\frac{1}{b-a}\\int_a^bf(x)dx$$ 积分中值定理保证存在 $\\xi\\in[a,b]$ 使 $f(\\xi)=\\bar f$。均方根值 $\\sqrt{\\frac{1}{b-a}\\int_a^bf^2(x)dx}$ 在电学（有效值）中常用，注意与平均值区分。",
        "formula": "$$\\bar f=\\frac{1}{b-a}\\int_a^bf(x)dx$$",
        "example": "求 $f(x)=\\sin x$ 在 $\\left[0,\\pi\\right]$ 上的平均值：$\\bar f=\\frac{1}{\\pi}\\int_0^{\\pi}\\sin x\\,dx=\\frac{2}{\\pi}\\approx0.637$。它不等于 $\\frac{\\sin0+\\sin\\pi}{2}=0$——正弦半个周期“拱起”部分贡献了全部面积，端点平均完全反映不出来。",
        "error": "常见错误：①用端点函数值的平均代替积分平均；②忘记除以区间长度 $b-a$；③平均值与均方根值混用（交流电有效值是均方根而非平均）；④不连续函数（有跳跃）时直接套公式而不检查可积性表述。",
    },
    "integral-application-modeling": {
        "intuition": "所有积分应用共用一套“微元法”思维：把整体切成无穷多个微小单元，写出每个单元的近似量（微元），再对微元求和取极限。识别“分布不均匀的量”是建模的第一步。",
        "definition": "微元法四步：①选变量与坐标系，确定积分区间；②在区间内任取一小段 $[x,x+dx]$，用“以常代变、以直代曲、以匀代不匀”写出所求量 $U$ 的微元 $$dU=f(x)dx$$ ③确认微元舍弃的是高阶小量（这一步保证正确性）；④积分 $U=\\int_a^bf(x)dx$ 并代数值。面积、体积、弧长、功、压力、平均值都是这套流程的实例。",
        "formula": "$$dU=f(x)dx\\;\\Longrightarrow\\;U=\\int_a^bf(x)dx$$",
        "example": "求抛物线 $y=x^2$ 与直线 $y=x$ 所围图形绕 $x$ 轴旋转一周的体积。交点 $x=0,1$；取 $[x,x+dx]$ 上的一小段，截面为垫圈：外半径 $x$、内半径 $x^2$，微元 $dV=\\pi\\left(x^2-x^4\\right)dx$，故 $V=\\pi\\int_0^1\\left(x^2-x^4\\right)dx=\\pi\\left(\\frac13-\\frac15\\right)=\\frac{2\\pi}{15}$。从微元到积分一气呵成。",
        "error": "常见错误：①微元写错阶（如把 $ds=\\sqrt{1+y'^2}dx$ 写成 $dx$，体积元素用面积元素代替）；②坐标系选择不当使被积函数或区间复杂；③微元中“以常代变”的近似不合法（舍弃项不是高阶小量）；④几何量（面积、体积）算出负值不回头检查上下曲线/内外半径的次序。",
    },
}


def phase5_standard_resources_for(code: str) -> list[tuple[str, str, str]]:
    """Resource rows for a non-golden chapter 3-6 point (5 authored + 2 shared)."""
    item = STANDARD[code]
    ref = STANDARD_CHAPTER_REF[code]
    rows = [
        ("intuition", "一句话直觉", item["intuition"]),
        ("definition", "定义与适用条件", item["definition"]),
        ("formula", "核心公式", item["formula"]),
        ("worked_example", "典型例题", item["example"]),
        ("common_error", "常见错误与提醒", item["error"]),
        ("summary", "小结与下一步",
         "先核对条件与结构，再按规范步骤完成计算，并检查结果的符号、量纲与适用范围。学完本节内容后进入正式练习巩固；若卡在前置环节，返回图谱复习直接前置知识点。"),
        ("source_reference", "来源与署名",
         f"项目原创中文教学内容；概念范围参考 OpenStax Calculus {ref}。未复制原文，使用时保留来源与许可证记录。"),
    ]
    return rows
