"""initial_migration

Revision ID: 7824223d8a63
Revises: 
Create Date: 2026-07-29 00:04:11.388065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7824223d8a63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_idempotency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('processed_at', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index('idx_ei_event_type', 'event_idempotency', ['event_type'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=20), nullable=True),
    sa.Column('high_category', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_summary', sa.Text(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expire_at', sa.Integer(), nullable=False),
    sa.Column('memory_strength', sa.Float(), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('last_accessed', sa.Integer(), nullable=True),
    sa.Column('access_count', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mem_expire_status', 'memories', ['expire_at', 'status'], unique=False)
    op.create_index('idx_mem_source_id', 'memories', ['source_id', 'memory_type'], unique=False)
    op.create_index('idx_mem_user_category', 'memories', ['user_id', 'high_category', 'category', 'status'], unique=False)
    op.create_index('idx_mem_user_status', 'memories', ['user_id', 'status'], unique=False)
    op.create_index('idx_mem_user_type', 'memories', ['user_id', 'memory_type', 'status'], unique=False)
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_table('migration_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_system', sa.String(length=50), nullable=True),
    sa.Column('target_system', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('migrated_count', sa.Integer(), nullable=True),
    sa.Column('failed_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=30), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('solution_steps', sa.JSON(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_categories', sa.String(length=200), nullable=True),
    sa.Column('knowledge_points', sa.String(length=500), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('complexity_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('correct_rate', sa.Float(), nullable=True),
    sa.Column('avg_time_spent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_question_category_difficulty', 'questions', ['category', 'difficulty'], unique=False)
    op.create_index('idx_question_source', 'questions', ['source'], unique=False)
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_is_active'), 'questions', ['is_active'], unique=False)
    op.create_index(op.f('ix_questions_question_type'), 'questions', ['question_type'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('full_profile_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.Integer(), nullable=False),
    sa.Column('expire_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('agent_strategy', sa.String(length=30), nullable=True),
    sa.Column('tools_used', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_created_at'), 'chat_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('error_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=64), nullable=False, comment='原始错题 ID'),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('original_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.String(length=30), nullable=True),
    sa.Column('mastery_level', sa.Integer(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_error_items_user', 'error_items', ['user_id', 'is_mastered'], unique=False)
    op.create_index('idx_error_items_user_item', 'error_items', ['user_id', 'item_id'], unique=True)
    op.create_index(op.f('ix_error_items_item_id'), 'error_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_error_items_user_id'), 'error_items', ['user_id'], unique=False)
    op.create_table('exam_papers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_time_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_papers_created_at'), 'exam_papers', ['created_at'], unique=False)
    op.create_index(op.f('ix_exam_papers_user_id'), 'exam_papers', ['user_id'], unique=False)
    op.create_table('learning_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=20), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('question_content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('sub_categories', sa.String(length=200), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('hint_count', sa.Integer(), nullable=True),
    sa.Column('tools_used', sa.String(length=200), nullable=True),
    sa.Column('error_category', sa.String(length=50), nullable=True),
    sa.Column('error_reason', sa.Text(), nullable=True),
    sa.Column('correction_suggestion', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_learning_errors', 'learning_records', ['user_id', 'category'], unique=False, postgresql_where='is_correct = FALSE')
    op.create_index('idx_learning_event_type', 'learning_records', ['event_type', 'created_at'], unique=False)
    op.create_index('idx_learning_user_category', 'learning_records', ['user_id', 'category'], unique=False)
    op.create_index('idx_learning_user_time', 'learning_records', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_learning_records_category'), 'learning_records', ['category'], unique=False)
    op.create_index(op.f('ix_learning_records_created_at'), 'learning_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_learning_records_event_type'), 'learning_records', ['event_type'], unique=False)
    op.create_index(op.f('ix_learning_records_question_id'), 'learning_records', ['question_id'], unique=False)
    op.create_index(op.f('ix_learning_records_user_id'), 'learning_records', ['user_id'], unique=False)
    op.create_table('memory_access_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('accessed_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mal_memory_id', 'memory_access_log', ['memory_id'], unique=False)
    op.create_index('idx_mal_user_time', 'memory_access_log', ['user_id', 'accessed_at'], unique=False)
    op.create_table('memory_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('memory_id', 'tag_name', name='uq_memory_tag')
    )
    op.create_index('idx_mtag_name', 'memory_tags', ['tag_name'], unique=False)
    op.create_table('migration_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('migration_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.String(length=100), nullable=True),
    sa.Column('error_type', sa.String(length=50), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['migration_id'], ['migration_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('skill_code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('category_path', sa.String(length=200), nullable=True),
    sa.Column('mastery_level', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('recent_streak', sa.Integer(), nullable=False),
    sa.Column('best_streak', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_practiced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mastered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evolution_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_code', name='uq_user_skill')
    )
    op.create_index('idx_us_skill_code', 'user_skills', ['skill_code'], unique=False)
    op.create_index('idx_us_user_mastery', 'user_skills', ['user_id', 'mastery_level'], unique=False)
    op.create_index('idx_us_user_status', 'user_skills', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_user_skills_user_id'), 'user_skills', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('learning_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learning_record_id'], ['learning_records.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_session_time', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_role'), 'chat_messages', ['role'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('exam_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paper_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=20), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('hints_used', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paper_id'], ['exam_papers.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_submissions')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_role'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index('idx_message_session_time', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_user_skills_user_id'), table_name='user_skills')
    op.drop_index('idx_us_user_status', table_name='user_skills')
    op.drop_index('idx_us_user_mastery', table_name='user_skills')
    op.drop_index('idx_us_skill_code', table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('migration_errors')
    op.drop_index('idx_mtag_name', table_name='memory_tags')
    op.drop_table('memory_tags')
    op.drop_index('idx_mal_user_time', table_name='memory_access_log')
    op.drop_index('idx_mal_memory_id', table_name='memory_access_log')
    op.drop_table('memory_access_log')
    op.drop_index(op.f('ix_learning_records_user_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_question_id'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_event_type'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_created_at'), table_name='learning_records')
    op.drop_index(op.f('ix_learning_records_category'), table_name='learning_records')
    op.drop_index('idx_learning_user_time', table_name='learning_records')
    op.drop_index('idx_learning_user_category', table_name='learning_records')
    op.drop_index('idx_learning_event_type', table_name='learning_records')
    op.drop_index('idx_learning_errors', table_name='learning_records', postgresql_where='is_correct = FALSE')
    op.drop_table('learning_records')
    op.drop_index(op.f('ix_exam_papers_user_id'), table_name='exam_papers')
    op.drop_index(op.f('ix_exam_papers_created_at'), table_name='exam_papers')
    op.drop_table('exam_papers')
    op.drop_index(op.f('ix_error_items_user_id'), table_name='error_items')
    op.drop_index(op.f('ix_error_items_item_id'), table_name='error_items')
    op.drop_index('idx_error_items_user_item', table_name='error_items')
    op.drop_index('idx_error_items_user', table_name='error_items')
    op.drop_table('error_items')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_index(op.f('ix_chat_sessions_created_at'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_questions_question_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_is_active'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_index('idx_question_source', table_name='questions')
    op.drop_index('idx_question_category_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_table('migration_status')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_index('idx_mem_user_type', table_name='memories')
    op.drop_index('idx_mem_user_status', table_name='memories')
    op.drop_index('idx_mem_user_category', table_name='memories')
    op.drop_index('idx_mem_source_id', table_name='memories')
    op.drop_index('idx_mem_expire_status', table_name='memories')
    op.drop_table('memories')
    op.drop_index('idx_ei_event_type', table_name='event_idempotency')
    op.drop_table('event_idempotency')
    # ### end Alembic commands ###
