"""Create seed questions Excel file."""
import pandas as pd

data = [
    {"id": "Q001", "content": "已知函数$f(x)=x^3-3x^2+2$，求$f'(x)$。", "question_type": "填空题", "options": "[]", "answer": "f'(x)=3x^2-6x", "analysis": "利用幂函数求导法则：$(x^n)'=nx^{n-1}$，分别对$x^3$、$-3x^2$、$2$求导即可。", "category": "导数", "sub_categories": "导数计算", "knowledge_points": '["导数定义","基本求导公式"]', "difficulty": 1, "estimated_time": 3, "source": "seed"},
    {"id": "Q002", "content": "求函数$f(x)=e^x\\sin x$的导数$f'(x)$。", "question_type": "选择题", "options": '["A. e^x sin x + e^x cos x","B. e^x sin x - e^x cos x","C. e^x cos x","D. e^x sin x + e^x"]', "answer": "A", "analysis": "利用乘法法则：$(uv)'=u'v+uv'$，其中$u=e^x$，$v=\\sin x$。", "category": "导数", "sub_categories": "导数计算", "knowledge_points": '["乘法法则","复合函数求导"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q003", "content": "已知$f(x)=\\ln(x^2+1)$，求$f'(x)$。", "question_type": "填空题", "options": "[]", "answer": "f'(x)=2x/(x^2+1)", "analysis": "利用链式法则：设$u=x^2+1$，则$f(u)=\\ln u$，$f'(x)=\\frac{1}{u}\\cdot u'=\\frac{2x}{x^2+1}$。", "category": "导数", "sub_categories": "导数计算", "knowledge_points": '["链式法则","对数函数求导"]', "difficulty": 3, "estimated_time": 3, "source": "seed"},
    {"id": "Q004", "content": "求函数$f(x)=\\frac{x^2+1}{x-1}$的导数。", "question_type": "填空题", "options": "[]", "answer": "f'(x)=(x^2-2x-1)/(x-1)^2", "analysis": "利用商法则：$(u/v)'=(u'v-uv')/v^2$，其中$u=x^2+1$，$v=x-1$。", "category": "导数", "sub_categories": "导数计算", "knowledge_points": '["商法则","导数应用"]', "difficulty": 4, "estimated_time": 5, "source": "seed"},
    {"id": "Q005", "content": "已知$f(x)=\\sin(2x+\\frac{\\pi}{3})$，求$f'(x)$。", "question_type": "填空题", "options": "[]", "answer": "f'(x)=2cos(2x+pi/3)", "analysis": "链式法则：先对外层三角函数求导，再对内层$2x+\\pi/3$求导。", "category": "导数", "sub_categories": "导数计算", "knowledge_points": '["链式法则","三角函数求导"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q006", "content": "若$f(x)$在$x=1$处可导，且$\\lim_{h\\to 0}\\frac{f(1+h)-f(1)}{h}=3$，则$f'(1)=$？", "question_type": "填空题", "options": "[]", "answer": "3", "analysis": "根据导数定义，$f'(x_0)=\\lim_{h\\to 0}\\frac{f(x_0+h)-f(x_0)}{h}$。", "category": "导数", "sub_categories": "导数定义", "knowledge_points": '["导数定义","极限"]', "difficulty": 1, "estimated_time": 3, "source": "seed"},
    {"id": "Q007", "content": "解不等式$2x^2-5x+2<0$。", "question_type": "选择题", "options": '["A. x<1/2 或 x>2","B. 1/2<x<2","C. x<2","D. x>1/2"]', "answer": "B", "analysis": "先解方程$2x^2-5x+2=0$得$x=1/2$或$x=2$，画二次函数图像，开口向上，小于0取中间。", "category": "不等式", "sub_categories": "一元二次不等式", "knowledge_points": '["一元二次不等式","二次函数"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q008", "content": "解不等式$\\frac{x-2}{x+1}>0$。", "question_type": "填空题", "options": "[]", "answer": "x<-1 或 x>2", "analysis": "分式不等式通过数轴标根法解决：分子零点$x=2$，分母零点$x=-1$。", "category": "不等式", "sub_categories": "分式不等式", "knowledge_points": '["分式不等式","数轴标根"]', "difficulty": 3, "estimated_time": 4, "source": "seed"},
    {"id": "Q009", "content": "已知$a>0,b>0$，且$a+b=4$，求$ab$的最大值。", "question_type": "填空题", "options": "[]", "answer": "4", "analysis": "由均值不等式：$ab\\leq(\\frac{a+b}{2})^2=4$，当$a=b=2$时取等号。", "category": "不等式", "sub_categories": "均值不等式", "knowledge_points": '["基本不等式","最值问题"]', "difficulty": 3, "estimated_time": 3, "source": "seed"},
    {"id": "Q010", "content": "已知集合$A=\\{x|x^2-3x+2=0\\}$，$B=\\{x|0<x<5,x\\in N\\}$，求$A\\cap B$。", "question_type": "填空题", "options": "[]", "answer": "{1,2}", "analysis": "解方程得$A=\\{1,2\\}$，$B=\\{1,2,3,4\\}$，交集为$\\{1,2\\}$。", "category": "集合", "sub_categories": "集合运算", "knowledge_points": '["集合运算","一元二次方程"]', "difficulty": 1, "estimated_time": 3, "source": "seed"},
    {"id": "Q011", "content": "已知全集$U=\\{1,2,3,4,5\\}$，$A=\\{1,2,3\\}$，$B=\\{2,3,4\\}$，求补集。", "question_type": "填空题", "options": "[]", "answer": "{1,4,5}", "analysis": "先求交集$A\\cap B=\\{2,3\\}$，再求补集。", "category": "集合", "sub_categories": "集合运算", "knowledge_points": '["集合运算","补集"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q012", "content": '命题"若x>1，则x^2>1"的逆否命题。', "question_type": "选择题", "options": '["A. 若x^2>1，则x>1","B. 若x^2<=1，则x<=1","C. 若x<=1，则x^2<=1","D. 若x^2>1，则x<=1"]', "answer": "B", "analysis": '原命题"若p则q"的逆否命题是"若非q则非p"。', "category": "集合", "sub_categories": "命题逻辑", "knowledge_points": '["命题","逆否命题"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q013", "content": "在$\\triangle ABC$中，已知$a=3$，$b=4$，$\\cos C=\\frac{1}{3}$，求$c$。", "question_type": "填空题", "options": "[]", "answer": "c=sqrt(17)", "analysis": "由余弦定理：$c^2=a^2+b^2-2ab\\cos C=9+16-2\\times3\\times4\\times\\frac{1}{3}=17$。", "category": "三角函数", "sub_categories": "解三角形", "knowledge_points": '["余弦定理","解三角形"]', "difficulty": 3, "estimated_time": 4, "source": "seed"},
    {"id": "Q014", "content": "在$\\triangle ABC$中，已知$\\sin A:\\sin B:\\sin C=3:4:5$，求$\\cos A$。", "question_type": "填空题", "options": "[]", "answer": "4/5", "analysis": "由正弦定理，$a:b:c=\\sin A:\\sin B:\\sin C=3:4:5$，设$a=3k,b=4k,c=5k$，由余弦定理：$\\cos A=\\frac{b^2+c^2-a^2}{2bc}=\\frac{16k^2+25k^2-9k^2}{40k^2}=\\frac{4}{5}$。", "category": "三角函数", "sub_categories": "解三角形", "knowledge_points": '["正弦定理","余弦定理"]', "difficulty": 4, "estimated_time": 5, "source": "seed"},
    {"id": "Q015", "content": "求$\\sin 75^\\circ$的值。", "question_type": "填空题", "options": "[]", "answer": "(sqrt(6)+sqrt(2))/4", "analysis": "$\\sin 75^\\circ=\\sin(45^\\circ+30^\\circ)=\\sin 45^\\circ\\cos 30^\\circ+\\cos 45^\\circ\\sin 30^\\circ$。", "category": "三角函数", "sub_categories": "三角恒等变换", "knowledge_points": '["两角和公式","特殊角三角函数值"]', "difficulty": 1, "estimated_time": 3, "source": "seed"},
    {"id": "Q016", "content": "已知$\\sin\\alpha=\\frac{3}{5}$，$\\alpha\\in(0,\\frac{\\pi}{2})$，求$\\cos 2\\alpha$。", "question_type": "填空题", "options": "[]", "answer": "7/25", "analysis": "$\\cos 2\\alpha=1-2\\sin^2\\alpha=1-2\\times(\\frac{3}{5})^2=\\frac{7}{25}$。", "category": "三角函数", "sub_categories": "三角恒等变换", "knowledge_points": '["二倍角公式","同角三角函数"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q017", "content": "求$\\lim_{x\\to 0}\\frac{\\sin 3x}{x}$。", "question_type": "填空题", "options": "[]", "answer": "3", "analysis": "利用重要极限：$\\lim_{x\\to 0}\\frac{\\sin x}{x}=1$，$\\lim_{x\\to 0}\\frac{\\sin 3x}{x}=3\\cdot\\lim_{x\\to 0}\\frac{\\sin 3x}{3x}=3$。", "category": "极限", "sub_categories": "极限计算", "knowledge_points": '["重要极限","极限运算"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q018", "content": "求$\\lim_{x\\to 1}\\frac{x^2-1}{x-1}$。", "question_type": "填空题", "options": "[]", "answer": "2", "analysis": "$\\lim_{x\\to 1}\\frac{x^2-1}{x-1}=\\lim_{x\\to 1}\\frac{(x-1)(x+1)}{x-1}=\\lim_{x\\to 1}(x+1)=2$。", "category": "极限", "sub_categories": "极限计算", "knowledge_points": '["极限运算","因式分解"]', "difficulty": 1, "estimated_time": 3, "source": "seed"},
    {"id": "Q019", "content": "已知数列$\\{a_n\\}$中，$a_1=2$，$a_{n+1}=2a_n+1$，求$a_5$。", "question_type": "填空题", "options": "[]", "answer": "47", "analysis": "递推：$a_2=5$，$a_3=11$，$a_4=23$，$a_5=47$。", "category": "数列", "sub_categories": "递推数列", "knowledge_points": '["递推数列","数列通项"]', "difficulty": 2, "estimated_time": 3, "source": "seed"},
    {"id": "Q020", "content": "在等差数列$\\{a_n\\}$中，已知$a_3=7$，$a_7=19$，求$a_{10}$。", "question_type": "填空题", "options": "[]", "answer": "28", "analysis": "$d=\\frac{a_7-a_3}{7-3}=\\frac{12}{4}=3$，$a_{10}=a_7+3d=19+9=28$。", "category": "数列", "sub_categories": "等差数列", "knowledge_points": '["等差数列","通项公式"]', "difficulty": 3, "estimated_time": 4, "source": "seed"},
]

df = pd.DataFrame(data, columns=["id", "content", "question_type", "options", "answer", "analysis", "category", "sub_categories", "knowledge_points", "difficulty", "estimated_time", "source"])
df.to_excel("data/seed_questions.xlsx", index=False, engine="openpyxl")
print(f"Created Excel with {len(df)} rows")