<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { renderMarkdown } from '@/utils/markdown'
import { useAssessmentStore } from '@/stores/assessmentStore'
const route=useRoute(),router=useRouter(),store=useAssessmentStore(),remaining=ref(0);let timer
const q=computed(()=>store.currentQuestion),timeText=computed(()=>`${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`)
onMounted(async()=>{await store.load(route.params.sessionId);if(store.session.status==='completed'){router.replace(`/apply/assessment/sessions/${route.params.sessionId}/result`);return}if(store.session.status==='created')await store.start();const start=new Date(store.session.started_at).getTime();remaining.value=Math.max(0,store.session.duration_limit_seconds-Math.floor((Date.now()-start)/1000));timer=setInterval(async()=>{remaining.value=Math.max(0,remaining.value-1);if(!remaining.value){clearInterval(timer);await finish()}},1000)})
onBeforeUnmount(()=>clearInterval(timer))
async function persist(){await store.save(q.value.question_id)}
async function finish(){await persist().catch(()=>{});await store.submit();router.push(`/apply/assessment/sessions/${route.params.sessionId}/result`)}
</script>
<template><AppShell><template #topbar-title>智能检测 · {{timeText}}</template><main v-if="q" class="runner"><header><span>{{store.session.planning_source==='llm'?'AI 蓝图':'规则蓝图'}}</span><span :class="store.saveState">{{store.saveState==='saving'?'保存中':store.saveState==='error'?'保存失败':'已保存'}}</span></header><p v-if="store.error" class="error" role="alert">{{store.error}}</p><section class="question"><div class="meta">第 {{q.position}} / {{store.session.questions.length}} 题 · {{q.question_type}}</div><div class="math" v-html="renderMarkdown(q.content)"/><div v-if="q.question_type==='choice'" class="options"><label v-for="o in q.options||[]" :key="o.id"><input v-model="store.answers[q.question_id]" type="radio" :value="o.id" @change="persist">{{o.id}}. <span v-html="renderMarkdown(o.text)"/></label></div><div v-else-if="q.question_type==='judge'" class="options"><label><input v-model="store.answers[q.question_id]" type="radio" value="true" @change="persist">对</label><label><input v-model="store.answers[q.question_id]" type="radio" value="false" @change="persist">错</label></div><input v-else v-model="store.answers[q.question_id]" class="answer" placeholder="输入答案" @blur="persist"></section><nav><button :disabled="store.currentIndex===0" @click="store.currentIndex--">上一题</button><div class="numbers"><button v-for="(item,index) in store.session.questions" :key="item.question_id" :class="{active:index===store.currentIndex,answered:store.answers[item.question_id]!==null&&store.answers[item.question_id]!==''}" @click="store.currentIndex=index">{{index+1}}</button></div><button v-if="store.currentIndex<store.session.questions.length-1" @click="store.currentIndex++">下一题</button><button v-else class="primary" :disabled="store.loading" @click="finish">交卷</button></nav></main><p v-else class="loading">正在恢复检测…</p></AppShell></template>
<style scoped>.runner{max-width:980px;margin:0 auto;padding:26px 24px 80px}.runner>header{display:flex;justify-content:space-between;color:var(--text-secondary)}.saving{color:var(--accent)}.error{color:var(--danger)}.question{margin-top:18px;padding:26px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}.meta{color:var(--text-tertiary);margin-bottom:16px}.math{line-height:1.75}.options{display:flex;flex-direction:column;gap:13px;margin-top:20px}.answer{box-sizing:border-box;width:100%;min-height:44px;margin-top:20px;padding:9px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);font:inherit}nav{display:flex;align-items:center;gap:12px;margin-top:22px}button{min-height:42px;padding:0 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);cursor:pointer}.numbers{display:flex;flex-wrap:wrap;gap:5px;justify-content:center;flex:1}.numbers button{min-width:38px;padding:0}.numbers .active{outline:2px solid var(--accent)}.numbers .answered{background:var(--accent-soft)}.primary{background:var(--accent);color:#fff;border-color:var(--accent)}.loading{padding:32px}@media(max-width:600px){.runner{padding:18px 14px 70px}.question{padding:18px}nav{flex-wrap:wrap}.numbers{order:3;flex-basis:100%}}</style>
