<script setup>
import { computed,onMounted } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import { renderMarkdown } from '@/utils/markdown'
import { useAssessmentStore } from '@/stores/assessmentStore'
import { errorCategoryLabel } from '@/utils/errorCategories'
const route=useRoute(),router=useRouter(),store=useAssessmentStore()
const results=computed(()=>store.result?.questions?.map(q=>({...q,...q.result}))||[])
const duration=computed(()=>store.result?.duration_seconds==null?'未记录':`${Math.floor(store.result.duration_seconds/60)} 分 ${store.result.duration_seconds%60} 秒`)
const quotaLabels={weakness:'薄弱点',due_review:'到期复习',current_chapter:'当前章节',challenge:'挑战题'}
const adjustmentLabels={difficulty_relaxed:'同知识点放宽难度',knowledge_point_relaxed:'同范围调剂知识点',recent_exposure_reused:'复用近期做过的正式题'}
const SCORING_LABELS={all_or_nothing:'全对得分（漏选或错选均不得分）',partial:'部分得分（漏选按正确项比例，出现错选即 0 分）',partial_minus:'部分得分 + 错选按比例扣分'}
const scoringLabel=(kind)=>SCORING_LABELS[kind]||kind
onMounted(()=>store.loadResult(route.params.sessionId))
function practiceWeakness(){const config=store.result?.next_practice_config;if(!config)return router.push('/apply/practice');router.push({path:'/apply/practice',query:{knowledge_points:(config.knowledge_point_codes||[]).join(','),question_count:config.question_count}})}
</script>
<template><AppShell><template #topbar-title>智能组卷报告</template><main v-if="store.result" class="report"><p class="eyebrow">{{store.result.planning_source==='llm'?'AI 个性化蓝图':'规则保障蓝图'}}</p><h1 class="t-1">本次智能试卷已完成</h1><p>得分 {{store.result.score}} / {{store.result.max_score}} · 答对 {{results.filter(r=>r.correct).length}} / {{results.length}} 题 · 用时 {{duration}}</p><section class="summary card card-pad"><h2 class="t-2">蓝图实际构成</h2><div class="quota"><span v-for="(count,kind) in store.result.quota_summary" :key="kind"><strong>{{count}}</strong>{{quotaLabels[kind]||kind}}</span></div><div v-if="store.result.blueprint_deviations?.length" class="adjustments"><h3>题库调剂说明</h3><p v-for="(row,index) in store.result.blueprint_deviations" :key="index">{{quotaLabels[row.quota_kind]||'组卷'}}：{{adjustmentLabels[row.reason]||row.reason}} {{row.count||''}}</p></div><p v-else>蓝图全部按原配额完成，无需题库调剂。</p></section><section v-if="store.result.knowledge_breakdown?.length" class="summary card card-pad"><h2 class="t-2">知识点表现</h2><p v-for="row in store.result.knowledge_breakdown" :key="row.knowledge_point_code">{{row.knowledge_point_code}}：{{row.correct}} / {{row.total}}（{{Math.round(row.accuracy*100)}}%）</p></section><section v-if="store.result.error_breakdown?.length" class="summary card card-pad"><h2 class="t-2">错因分布</h2><p v-for="row in store.result.error_breakdown" :key="row.category">{{errorCategoryLabel(row.category)}}：{{row.count}} 题</p></section><section v-for="item in results" :key="item.question_id" :class="['item card card-pad',item.correct?'ok':'bad']"><header>第 {{item.position}} 题 · {{item.correct?'答对':'答错'}}</header><div class="math" v-html="renderMarkdown(item.content)"/><p>你的答案：{{Array.isArray(item.your_answer)?item.your_answer.join('、'):item.your_answer}}</p><p>正确答案：{{item.correct_answer}}</p><p v-if="item.scoring" class="scoring-note">多选计分：{{scoringLabel(item.scoring)}} · 本题得分比例 {{Math.round((item.partial_credit??(item.correct?1:0))*100)}}%</p><aside v-if="item.selection_explanation||item.selection_reason"><strong>为什么选择这道题</strong><span>{{item.selection_explanation?.evidence_summary||item.selection_reason}}</span><small v-if="item.selection_explanation?.adjustment">{{adjustmentLabels[item.selection_explanation.adjustment]||item.selection_explanation.adjustment}}</small></aside><div v-if="item.analysis" class="math" v-html="renderMarkdown(item.analysis)"/></section><footer><BaseButton variant="secondary" size="lg" :disabled="!store.result.next_practice_config" @click="practiceWeakness">按薄弱点专项练习</BaseButton><BaseButton variant="primary" size="lg" @click="router.push('/apply')">返回学以致用</BaseButton></footer></main><p v-else class="loading" role="status">正在生成智能组卷报告…</p></AppShell></template>
<style scoped>.report{max-width:900px;margin:0 auto;padding:38px 24px 80px}.eyebrow{display:inline-flex;align-items:center;height:26px;padding:0 12px;border-radius:var(--r-pill);border:1px solid var(--border);background:var(--surface);font-size:12px;color:var(--ink-2);font-weight:500;box-shadow:var(--shadow-1)}.report h1{margin:12px 0 6px}.report>p,.summary>p{color:var(--ink-2)}.report>p{margin:0}.summary,.item{margin-top:16px}.summary h2{margin:0 0 12px}.quota{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.quota span{display:grid;gap:3px;padding:12px;border-radius:10px;border:1px solid var(--border);background:var(--surface-2);color:var(--ink-2)}.quota strong{font-size:22px;color:var(--ink-1)}.adjustments{margin-top:16px;padding:14px;border-radius:10px;background:var(--surface-2)}.adjustments h3{font-size:15px;margin:0}.adjustments p{color:var(--ink-2);margin-bottom:0}.item{border-left-width:4px}.item.ok{border-left-color:var(--green)}.item.bad{border-left-color:var(--rose)}.item header{font-weight:600}.item p{color:var(--ink-2)}.scoring-note{color:var(--ink-3)!important;font-size:13px}.item aside{display:grid;gap:5px;margin:14px 0;padding:12px;border-radius:10px;background:var(--accent-soft)}.item aside span,.item aside small{color:var(--ink-2)}.math{line-height:1.7}footer{display:flex;gap:12px;margin-top:28px}.loading{padding:32px}@media(max-width:600px){.report{padding:28px 16px 64px}.quota{grid-template-columns:repeat(2,minmax(0,1fr))}footer{flex-direction:column}footer button{width:100%}}</style>
