<script setup>
import { computed,onMounted } from 'vue'
import { useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { useAssessmentStore } from '@/stores/assessmentStore'
const router=useRouter(),store=useAssessmentStore()
const hasReadiness=computed(()=>store.readiness!==null)
const ready=computed(()=>hasReadiness.value&&store.readiness.available_questions>=store.config.question_count)
const inventoryInsufficient=computed(()=>hasReadiness.value&&!store.error&&!store.loading&&!ready.value)
onMounted(()=>store.loadReadiness().catch(()=>{}))
async function begin(){await store.create();router.push(`/apply/assessment/sessions/${store.session.session_id}`)}
</script>
<template><AppShell><template #topbar-title>智能检测</template><main class="setup"><button class="back" @click="router.push('/apply')">返回学以致用</button><h1>智能检测</h1><p>系统结合你的学习画像与近期作答规划检测重点，题目全部来自已审核题库。</p><p v-if="store.error" class="error" role="alert">题库信息加载失败：{{store.error}}。请确认后端服务已启动后重试。</p><p v-else-if="store.loading&&!hasReadiness" class="status" role="status">正在加载正式题库…</p><section v-if="store.readiness" class="evidence"><h2>可用学习证据</h2><div class="metrics"><span>技能 {{store.readiness.evidence.skill_count}}</span><span>错题组 {{store.readiness.evidence.unmastered_error_groups}}</span><span>近期作答 {{store.readiness.evidence.recent_attempts}}</span><span>正式题 {{store.readiness.available_questions}}</span></div><p>{{store.readiness.evidence.has_history?'将优先检测薄弱点；规划失败时自动使用规则蓝图。':'当前数据较少，将使用冷启动覆盖规则。'}}</p></section><section class="panel"><label>检测目标<select v-model="store.config.goal"><option value="weakness_check">薄弱点检测</option><option value="stage_retest">阶段复测</option><option value="review_due">复习检测</option><option value="comprehensive">综合诊断</option></select></label><label>检测时长<select v-model.number="store.config.duration_minutes"><option v-for="n in [15,30,45,60]" :key="n" :value="n">{{n}} 分钟</option></select></label><label>检测强度<select v-model="store.config.intensity"><option value="foundation">基础确认</option><option value="standard">标准检测</option><option value="advanced">进阶挑战</option></select></label><label>题量<select v-model.number="store.config.question_count"><option v-for="n in [5,10,15,20]" :key="n" :value="n">{{n}} 题</option></select></label><button :disabled="!ready||store.loading" @click="begin">{{store.loading&&hasReadiness?'正在规划蓝图…':'生成智能检测'}}</button><p v-if="inventoryInsufficient" class="error">当前正式题库存不足，请减少题量。</p></section></main></AppShell></template>
<style scoped>.setup{max-width:880px;margin:0 auto;padding:34px 24px 70px}.back{border:0;background:none;color:var(--accent);padding:0;font:inherit;cursor:pointer}h1{margin:14px 0 8px}.setup>p{color:var(--text-secondary)}.status{color:var(--text-secondary)}.evidence,.panel{margin-top:22px;padding:22px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}h2{font-size:18px;margin-top:0}.metrics{display:flex;flex-wrap:wrap;gap:10px}.metrics span{padding:7px 10px;border-radius:var(--radius-pill);background:var(--surface-muted);color:var(--text-secondary)}.evidence p{color:var(--text-secondary)}.panel{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.panel label{display:flex;flex-direction:column;gap:8px;color:var(--text-secondary)}select{min-height:42px;padding:0 9px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary)}.panel button{min-height:46px;border:0;border-radius:var(--radius-sm);background:var(--accent);color:#fff;font:inherit;cursor:pointer}.error{color:var(--danger)!important}@media(max-width:600px){.setup{padding:24px 16px}.panel{grid-template-columns:1fr}}</style>
