<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { renderMarkdown } from '@/utils/markdown'
import { useAssessmentStore } from '@/stores/assessmentStore'
const route=useRoute(),router=useRouter(),store=useAssessmentStore(),remaining=ref(0),finishing=ref(false);let timer
const q=computed(()=>store.currentQuestion),timeText=computed(()=>`${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`)
const unanswered=computed(()=>store.session?.questions?.filter(item=>store.answers[item.question_id]===null||store.answers[item.question_id]==='').length||0)
onMounted(async()=>{await store.load(route.params.sessionId);if(store.session.status==='completed'){router.replace(`/apply/assessment/sessions/${route.params.sessionId}/result`);return}if(store.session.status==='created')await store.start();const start=new Date(store.session.started_at).getTime();remaining.value=Math.max(0,store.session.duration_limit_seconds-Math.floor((Date.now()-start)/1000));timer=setInterval(async()=>{remaining.value=Math.max(0,remaining.value-1);if(!remaining.value){clearInterval(timer);await finish(true)}},1000)})
onBeforeUnmount(()=>clearInterval(timer))
async function persist(){await store.save(q.value.question_id)}
async function finish(timeout=false){if(finishing.value)return;if(!timeout&&unanswered.value&&!window.confirm(`还有 ${unanswered.value} 题未作答，确定交卷吗？`))return;finishing.value=true;try{await persist().catch(()=>{});await store.submit();router.push(`/apply/assessment/sessions/${route.params.sessionId}/result`)}finally{finishing.value=false}}
</script>
<template><AppShell><template #topbar-title>智能组卷 · {{timeText}}</template><main v-if="q" class="runner"><header><span>{{store.session.planning_source==='llm'?'AI 个性化蓝图':'规则保障蓝图'}}</span><span :class="store.saveState" role="status">{{store.saveState==='saving'?'保存中':store.saveState==='unsaved'?'待保存':store.saveState==='error'?'保存失败，请重试':'已保存'}}</span></header><p v-if="store.error" class="error" role="alert">{{store.error}}</p><section class="question"><div class="meta">第 {{q.position}} / {{store.session.questions.length}} 题 · {{q.question_type}}</div><div class="math" v-html="renderMarkdown(q.content)"/><div v-if="q.question_type==='choice'" class="options"><label v-for="o in q.options||[]" :key="o.id"><input v-model="store.answers[q.question_id]" type="radio" :value="o.id" @change="persist">{{o.id}}. <span v-html="renderMarkdown(o.text)"/></label></div><div v-else-if="q.question_type==='judge'" class="options"><label><input v-model="store.answers[q.question_id]" type="radio" value="true" @change="persist">对</label><label><input v-model="store.answers[q.question_id]" type="radio" value="false" @change="persist">错</label></div><label v-else class="answer-label">你的答案<input v-model="store.answers[q.question_id]" class="answer" placeholder="输入答案" @input="store.markDirty(q.question_id)" @blur="persist"></label></section><nav aria-label="题目导航"><button :disabled="store.currentIndex===0" @click="store.currentIndex--">上一题</button><div class="numbers"><button v-for="(item,index) in store.session.questions" :key="item.question_id" :aria-label="`第 ${index+1} 题${store.answers[item.question_id]!==null&&store.answers[item.question_id]!==''?'，已作答':'，未作答'}`" :aria-current="index===store.currentIndex?'step':undefined" :class="{active:index===store.currentIndex,answered:store.answers[item.question_id]!==null&&store.answers[item.question_id]!==''}" @click="store.currentIndex=index">{{index+1}}</button></div><button v-if="store.currentIndex<store.session.questions.length-1" @click="store.currentIndex++">下一题</button><button v-else class="primary" :disabled="store.loading||finishing" @click="finish(false)">{{finishing?'正在交卷…':unanswered?`交卷（${unanswered} 题未答）`:'交卷'}}</button></nav></main><p v-else class="loading" role="status">正在恢复智能试卷…</p></AppShell></template>
<style scoped>.runner{max-width:980px;margin:0 auto;padding:26px 24px 80px}.runner>header{display:flex;justify-content:space-between;gap:16px;color:var(--text-secondary)}.saving,.unsaved{color:var(--accent)}.error{color:var(--danger)}.question{margin-top:18px;padding:26px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}.meta{color:var(--text-tertiary);margin-bottom:16px}.math{line-height:1.75}.options{display:flex;flex-direction:column;gap:13px;margin-top:20px}.options label{min-height:44px;display:flex;align-items:center;gap:8px}.answer-label{display:grid;gap:8px;margin-top:20px;color:var(--text-secondary)}.answer{box-sizing:border-box;width:100%;min-height:44px;padding:9px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);font:inherit}nav{display:flex;align-items:center;gap:12px;margin-top:22px}button{min-height:44px;padding:0 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);cursor:pointer}.numbers{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;flex:1}.numbers button{min-width:44px;padding:0}.numbers .active{outline:2px solid var(--accent);outline-offset:2px}.numbers .answered{background:var(--accent-soft)}.primary{background:var(--accent);color:#fff;border-color:var(--accent)}button:disabled{opacity:.45;cursor:not-allowed}button:focus-visible,.answer:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.loading{padding:32px}@media(max-width:600px){.runner{padding:18px 14px 70px}.question{padding:18px}nav{flex-wrap:wrap}.numbers{order:3;flex-basis:100%}.primary{flex:1}}</style>
