<script setup>
import { computed,onMounted } from 'vue'
import { useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { useAssessmentStore } from '@/stores/assessmentStore'
const router=useRouter(),store=useAssessmentStore()
const quotaOrder=['weakness','due_review','current_chapter','challenge']
const quotaLabels={weakness:'薄弱点',due_review:'到期复习',current_chapter:'当前章节',challenge:'挑战题'}
const presets={weakness_check:[.5,.2,.2,.1],stage_retest:[.35,.3,.25,.1],review_due:[.25,.5,.15,.1],comprehensive:[.3,.25,.3,.15]}
const estimatedQuotas=computed(()=>{const raw=presets[store.config.goal].map(v=>v*store.config.question_count),values=raw.map(Math.floor);let left=store.config.question_count-values.reduce((a,b)=>a+b,0);[...raw.keys()].sort((a,b)=>(raw[b]-values[b])-(raw[a]-values[a])||a-b).slice(0,left).forEach(i=>values[i]++);return quotaOrder.map((kind,i)=>({kind,label:quotaLabels[kind],count:values[i]}))})
const hasReadiness=computed(()=>store.readiness!==null)
const ready=computed(()=>hasReadiness.value&&store.readiness.max_question_count>=store.config.question_count)
const inventoryInsufficient=computed(()=>hasReadiness.value&&!store.error&&!store.loading&&!ready.value)
onMounted(()=>store.loadReadiness().catch(()=>{}))
async function begin(){await store.create();router.push(`/apply/assessment/sessions/${store.session.session_id}`)}
</script>
<template><AppShell><template #topbar-title>智能组卷</template><main class="setup"><button class="back" @click="router.push('/apply')">返回学以致用</button><p class="eyebrow">智能组卷</p><h1>让每一道题都有学习依据</h1><p>AI 只规划组卷蓝图，题目全部来自已审核题库；AI 不可用时会自动切换规则蓝图。</p><p v-if="store.error" class="error" role="alert">智能组卷信息加载失败：{{store.error}}。请重试或返回使用自主考试。</p><p v-else-if="store.loading&&!hasReadiness" class="status" role="status">正在读取题库与学习证据…</p><section v-if="store.readiness" class="evidence"><h2>本次可用依据</h2><div class="metrics"><span>薄弱点 {{store.readiness.evidence.weakness_points}}</span><span>到期复习 {{store.readiness.evidence.due_review_points}}</span><span>当前章节 {{store.readiness.evidence.current_chapter_points}}</span><span>挑战点 {{store.readiness.evidence.challenge_points}}</span><span>正式题 {{store.readiness.available_questions}}</span></div><p>{{store.readiness.evidence.has_history?'系统会按目标分配配额，并在题目不足时留下调剂说明。':'学习数据较少，将优先覆盖当前章节，并随着作答逐步个性化。'}}</p></section><section v-if="store.readiness" class="panel"><label>组卷目标<select v-model="store.config.goal"><option value="weakness_check">薄弱点检测</option><option value="stage_retest">阶段复测</option><option value="review_due">到期复习</option><option value="comprehensive">综合诊断</option></select></label><label>当前章节<select v-model="store.config.current_chapter_id"><option :value="null">由系统按范围覆盖</option><option v-for="chapter in store.readiness.chapters" :key="chapter.id" :value="chapter.id">{{chapter.name}}</option></select></label><label>作答时长<select v-model.number="store.config.duration_minutes"><option v-for="n in [15,30,45,60]" :key="n" :value="n">{{n}} 分钟</option></select></label><label>检测强度<select v-model="store.config.intensity"><option value="foundation">基础确认</option><option value="standard">标准检测</option><option value="advanced">进阶挑战</option></select></label><label>题量<select v-model.number="store.config.question_count"><option v-for="n in [5,10,15,20]" :key="n" :value="n">{{n}} 题</option></select></label><div class="quota-preview" aria-label="预计蓝图构成"><strong>预计蓝图</strong><span v-for="item in estimatedQuotas" :key="item.kind">{{item.label}} {{item.count}} 题</span><small>实际配额会依据可用证据和正式题库存确定性调剂。</small></div><button :disabled="!ready||store.loading" @click="begin">{{store.loading&&hasReadiness?'正在规划并校验蓝图…':'生成智能试卷'}}</button><p v-if="inventoryInsufficient" class="error">当前最多可生成 {{store.readiness.max_question_count}} 题，请减少题量或改用其他课程范围。</p></section></main></AppShell></template>
<style scoped>.setup{max-width:880px;margin:0 auto;padding:34px 24px 70px}.back{min-height:44px;border:0;background:none;color:var(--accent);padding:0;font:inherit;cursor:pointer}.eyebrow{color:var(--accent)!important;font-weight:600;margin:8px 0 0}h1{margin:4px 0 8px}.setup>p{color:var(--text-secondary)}.status{color:var(--text-secondary)}.evidence,.panel{margin-top:22px;padding:22px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}h2{font-size:18px;margin-top:0}.metrics{display:flex;flex-wrap:wrap;gap:10px}.metrics span,.quota-preview span{padding:7px 10px;border-radius:var(--radius-pill);background:var(--surface-muted);color:var(--text-secondary)}.evidence p{color:var(--text-secondary)}.panel{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.panel label{display:flex;flex-direction:column;gap:8px;color:var(--text-secondary)}select{box-sizing:border-box;min-height:44px;padding:0 10px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);font:inherit}.quota-preview{grid-column:1/-1;display:flex;flex-wrap:wrap;align-items:center;gap:8px;padding:16px;border-radius:var(--radius-md);background:var(--surface-muted)}.quota-preview strong,.quota-preview small{flex-basis:100%}.quota-preview small{color:var(--text-secondary)}.panel button{min-height:46px;border:0;border-radius:var(--radius-sm);background:var(--accent);color:#fff;font:inherit;cursor:pointer}.panel button:disabled{opacity:.45;cursor:not-allowed}.panel button:focus-visible,.back:focus-visible,select:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.error{color:var(--danger)!important}@media(max-width:600px){.setup{padding:24px 16px}.panel{grid-template-columns:1fr}.quota-preview{grid-column:auto}}</style>
