<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import ExerciseShell from '@/components/exercise/ExerciseShell.vue'
import QuestionAnswer from '@/components/exercise/QuestionAnswer.vue'
import QuestionNavigator from '@/components/exercise/QuestionNavigator.vue'
import SubmitOverview from '@/components/common/SubmitOverview.vue'
import { useAssessmentStore } from '@/stores/assessmentStore'
const route=useRoute(),router=useRouter(),store=useAssessmentStore(),remaining=ref(0),finishing=ref(false),overviewOpen=ref(false);let timer,serverRemainingMs=0,monotonicStart=0
const q=computed(()=>store.currentQuestion),timeText=computed(()=>`${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`)
const unanswered=computed(()=>store.session?.questions?.filter(item=>{const v=store.answers[item.question_id];return Array.isArray(v)?!v.length:v===null||v===undefined||v===''}).length||0)
onMounted(async()=>{await store.load(route.params.sessionId);if(store.session.status==='completed'){router.replace(`/apply/assessment/sessions/${route.params.sessionId}/result`);return}if(store.session.status==='created')await store.start();anchor();sync();timer=setInterval(async()=>{sync();if(!remaining.value){clearInterval(timer);await finish(true)}},1000)})
onBeforeUnmount(()=>clearInterval(timer))
function anchor(){serverRemainingMs=store.session.deadline_at&&store.session.server_time?Math.max(0,new Date(store.session.deadline_at)-new Date(store.session.server_time)):Math.max(0,store.session.duration_limit_seconds*1000-(Date.now()-new Date(store.session.started_at)));monotonicStart=performance.now()}
function sync(){remaining.value=Math.max(0,Math.ceil((serverRemainingMs-(performance.now()-monotonicStart))/1000))}
function changed(immediate){store.markDirty(q.value.question_id);if(immediate)persist();else setTimeout(()=>persist(),500)}
async function persist(){await store.save(q.value.question_id).catch(()=>{});if(store.session.status==='completed'){router.replace(`/apply/assessment/sessions/${route.params.sessionId}/result`);return true}return false}
async function finish(timeout=false){if(finishing.value)return;if(!timeout&&!overviewOpen.value){overviewOpen.value=true;return}overviewOpen.value=false;finishing.value=true;try{await persist();if(store.session.status!=='completed')await store.submit();router.replace(`/apply/assessment/sessions/${route.params.sessionId}/result`)}finally{finishing.value=false}}
function jump(index){overviewOpen.value=false;store.currentIndex=index}
</script>
<template><AppShell><template #topbar-title>智能检测</template><ExerciseShell v-if="q" :question="q" :total="store.session.questions.length" :status-text="store.session.planning_source==='llm'?'AI 个性化蓝图':'规则保障蓝图'" :timer-text="timeText"><template #save-state><span :class="store.saveState" role="status">{{store.saveState==='saving'?'保存中…':store.saveState==='unsaved'?'待保存':store.saveState==='error'?'保存失败':'已保存'}}</span></template><template #alert><p v-if="store.error" class="error" role="alert">{{store.error}}</p></template><QuestionAnswer v-model="store.answers[q.question_id]" :question="q" @commit="changed"/><template #actions><nav><button :disabled="store.currentIndex===0" @click="store.currentIndex--">上一题</button><QuestionNavigator :questions="store.session.questions" :answers="store.answers" :current-index="store.currentIndex" @jump="jump"/><button v-if="store.currentIndex<store.session.questions.length-1" @click="store.currentIndex++">下一题</button><button v-else class="primary" :disabled="store.loading||finishing" @click="finish(false)">{{unanswered?`交卷（${unanswered}题未答）`:'交卷'}}</button></nav></template></ExerciseShell><p v-else class="loading">正在恢复检测…</p><SubmitOverview :visible="overviewOpen" :questions="store.session?.questions||[]" :answers="store.answers" :current-index="store.currentIndex" :submitting="store.loading||finishing" title="交卷前总览 · 智能检测" @confirm="finish(false)" @cancel="overviewOpen=false" @jump="jump"/></AppShell></template>
<style scoped>nav{display:flex;align-items:center;gap:12px;margin-top:22px}button{min-height:44px;padding:0 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);cursor:pointer}.primary{background:var(--accent);color:#fff;border-color:var(--accent)}.error{color:var(--danger)}.saving,.unsaved{color:var(--accent)}.loading{padding:32px}@media(max-width:600px){nav{flex-wrap:wrap}nav :deep(.navigator){order:3;flex-basis:100%}}</style>
