<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import ExerciseShell from '@/components/exercise/ExerciseShell.vue'
import QuestionAnswer from '@/components/exercise/QuestionAnswer.vue'
import QuestionNavigator from '@/components/exercise/QuestionNavigator.vue'
import SubmitOverview from '@/components/common/SubmitOverview.vue'
import { useExamStore } from '@/stores/examStore'
const route=useRoute(),router=useRouter(),store=useExamStore(),remaining=ref(0),overviewOpen=ref(false);let clock,snapshotClock,serverRemainingMs=0,monotonicStart=0;const timers=new Map()
const q=computed(()=>store.currentQuestion),timeText=computed(()=>`${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`),answeredCount=computed(()=>Object.values(store.answers).filter(v=>Array.isArray(v)?v.length:v!==null&&v!==undefined&&v!=='').length)
onMounted(async()=>{await store.load(route.params.sessionId);if(store.session.status==='completed'){router.replace(`/apply/exam/sessions/${route.params.sessionId}/report`);return}if(store.session.status==='created')await store.start();serverRemainingMs=Math.max(0,new Date(store.session.deadline_at)-new Date(store.session.server_time));monotonicStart=performance.now();sync();clock=setInterval(async()=>{sync();if(!remaining.value){clearInterval(clock);await finish(true)}},1000);snapshotClock=setInterval(()=>store.saveRecoverySnapshot().catch(()=>{}),30000)})
onBeforeUnmount(()=>{clearInterval(clock);clearInterval(snapshotClock);store.saveRecoverySnapshot().catch(()=>{});for(const timer of timers.values())clearTimeout(timer)})
function sync(){remaining.value=Math.max(0,Math.ceil((serverRemainingMs-(performance.now()-monotonicStart))/1000))}
function schedule(immediate){const id=q.value.question_id;store.markDirty(id);if(timers.has(id))clearTimeout(timers.get(id));timers.set(id,setTimeout(()=>store.save(id).catch(()=>{}),immediate?0:600))}
async function move(index){if(q.value)await store.save(q.value.question_id).catch(()=>{});store.currentIndex=index;store.saveRecoverySnapshot().catch(()=>{})}
async function finish(timeout=false){for(const timer of timers.values())clearTimeout(timer);if(!timeout&&!overviewOpen.value){overviewOpen.value=true;return}overviewOpen.value=false;await store.submit();router.replace(`/apply/exam/sessions/${route.params.sessionId}/report`)}
function jump(index){overviewOpen.value=false;move(index)}
</script>
<template><AppShell><template #topbar-title>测试</template><ExerciseShell v-if="q" :question="q" :total="store.session.questions.length" :status-text="`已作答 ${answeredCount} / ${store.session.questions.length}`" :timer-text="timeText"><template #save-state><span :class="store.saveState" role="status">{{store.saveState==='saving'?'保存中…':store.saveState==='error'?'保存失败':store.saveState==='unsaved'?'等待保存':'已保存'}}</span></template><template #alert><p v-if="store.error" class="error" role="alert">{{store.error}}</p></template><QuestionAnswer v-model="store.answers[q.question_id]" :question="q" @commit="schedule"/><template #actions><nav><button :disabled="store.currentIndex===0" @click="move(store.currentIndex-1)">上一题</button><QuestionNavigator :questions="store.session.questions" :answers="store.answers" :current-index="store.currentIndex" @jump="jump"/><button v-if="store.currentIndex<store.session.questions.length-1" @click="move(store.currentIndex+1)">下一题</button><button v-else class="primary" :disabled="store.loading" @click="finish(false)">交卷</button></nav></template></ExerciseShell><p v-else class="loading">正在恢复测试…</p><SubmitOverview :visible="overviewOpen" :questions="store.session?.questions||[]" :answers="store.answers" :current-index="store.currentIndex" :submitting="store.loading" title="交卷前总览 · 测试" @confirm="finish(false)" @cancel="overviewOpen=false" @jump="jump"/></AppShell></template>
<style scoped>nav{display:flex;align-items:center;gap:12px;margin-top:22px}button{min-height:44px;padding:0 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);cursor:pointer}.primary{background:var(--accent);color:#fff;border-color:var(--accent)}.error{color:var(--danger)}.saving,.unsaved{color:var(--accent)}.loading{padding:32px}@media(max-width:600px){nav{flex-wrap:wrap}nav :deep(.navigator){order:3;flex-basis:100%}}</style>
