<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { renderMarkdown } from '@/utils/markdown'
import { useExamStore } from '@/stores/examStore'
const route=useRoute(),router=useRouter(),store=useExamStore(),remaining=ref(0);let clock;const timers=new Map()
const q=computed(()=>store.currentQuestion),timeText=computed(()=>`${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`)
const answeredCount=computed(()=>Object.values(store.answers).filter(value=>value!==null&&value!=='').length)
function syncClock(){const deadline=new Date(store.session.deadline_at).getTime();remaining.value=Math.max(0,Math.ceil((deadline-Date.now())/1000))}
onMounted(async()=>{await store.load(route.params.sessionId);if(store.session.status==='completed'){router.replace(`/apply/exam/sessions/${route.params.sessionId}/report`);return}if(store.session.status==='created')await store.start();syncClock();clock=setInterval(async()=>{syncClock();if(!remaining.value){clearInterval(clock);await finish(true)}},1000)})
onBeforeUnmount(()=>{clearInterval(clock);for(const timer of timers.values())clearTimeout(timer)})
function scheduleSave(id, immediate=false){store.markDirty(id);if(timers.has(id))clearTimeout(timers.get(id));timers.set(id,setTimeout(()=>store.save(id).catch(()=>{}),immediate?0:600))}
async function move(index){if(q.value)await store.save(q.value.question_id).catch(()=>{});store.currentIndex=index}
async function finish(timeout=false){for(const timer of timers.values())clearTimeout(timer);if(!timeout){const missing=store.session.questions.length-answeredCount.value;if(!globalThis.confirm(`确认交卷吗？还有 ${missing} 题未作答。`))return}await store.submit();router.replace(`/apply/exam/sessions/${route.params.sessionId}/report`)}
</script>
<template><AppShell><template #topbar-title>自主考试 · <span class="timer">{{timeText}}</span></template><main v-if="q" class="runner"><header><span>已作答 {{answeredCount}} / {{store.session.questions.length}}</span><span :class="store.saveState" role="status">{{store.saveState==='saving'?'保存中…':store.saveState==='error'?'保存失败':store.saveState==='unsaved'?'等待保存':'已保存'}}</span></header><p v-if="store.error" class="error" role="alert">{{store.error}}</p><section class="question"><div class="meta">第 {{q.position}} / {{store.session.questions.length}} 题 · {{q.question_type}}</div><div class="math" v-html="renderMarkdown(q.content)"/><div v-if="q.question_type==='choice'" class="options"><label v-for="o in q.options||[]" :key="o.id"><input v-model="store.answers[q.question_id]" type="radio" :value="o.id" @change="scheduleSave(q.question_id,true)">{{o.id}}. <span v-html="renderMarkdown(o.text)"/></label></div><div v-else-if="q.question_type==='judge'" class="options"><label><input v-model="store.answers[q.question_id]" type="radio" value="true" @change="scheduleSave(q.question_id,true)">对</label><label><input v-model="store.answers[q.question_id]" type="radio" value="false" @change="scheduleSave(q.question_id,true)">错</label></div><input v-else v-model="store.answers[q.question_id]" class="answer" placeholder="输入答案" @input="scheduleSave(q.question_id)" @blur="scheduleSave(q.question_id,true)"></section><nav><button :disabled="store.currentIndex===0" @click="move(store.currentIndex-1)">上一题</button><div class="numbers"><button v-for="(item,index) in store.session.questions" :key="item.question_id" :class="{active:index===store.currentIndex,answered:store.answers[item.question_id]!==null&&store.answers[item.question_id]!==''}" :aria-label="`第 ${index+1} 题${store.answers[item.question_id]?'，已作答':''}`" @click="move(index)">{{index+1}}</button></div><button v-if="store.currentIndex<store.session.questions.length-1" @click="move(store.currentIndex+1)">下一题</button><button v-else class="primary" :disabled="store.loading" @click="finish(false)">交卷</button></nav></main><p v-else class="loading" role="status">正在恢复考试…</p></AppShell></template>
<style scoped>.runner{max-width:980px;margin:0 auto;padding:26px 24px 80px}.runner>header{display:flex;justify-content:space-between;color:var(--text-secondary)}.timer{font-variant-numeric:tabular-nums}.saving,.unsaved{color:var(--accent)}.error{color:var(--danger)}.question{margin-top:18px;padding:26px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}.meta{color:var(--text-tertiary);margin-bottom:16px}.math{line-height:1.75}.options{display:flex;flex-direction:column;gap:8px;margin-top:20px}.options label{display:flex;align-items:center;gap:8px;min-height:44px}.answer{box-sizing:border-box;width:100%;min-height:44px;margin-top:20px;padding:9px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);font:inherit;background:var(--surface);color:var(--text-primary)}nav{display:flex;align-items:center;gap:12px;margin-top:22px}button{min-height:44px;padding:0 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);cursor:pointer}.numbers{display:flex;flex-wrap:wrap;gap:8px;justify-content:center;flex:1}.numbers button{min-width:44px;padding:0}.numbers .active{outline:2px solid var(--accent)}.numbers .answered{background:var(--accent-soft)}.primary{background:var(--accent);color:#fff;border-color:var(--accent)}.loading{padding:32px}@media(max-width:600px){.runner{padding:18px 14px 70px}.question{padding:18px}nav{flex-wrap:wrap}.numbers{order:3;flex-basis:100%}}</style>
