<script setup>
import { computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft } from 'lucide-vue-next'
import AppShell from '@/components/shell/AppShell.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import KnowledgeRangePicker from '@/components/common/KnowledgeRangePicker.vue'
import { useExamStore } from '@/stores/examStore'
const router = useRouter(), store = useExamStore()
const labels = { choice: '选择题', judge: '判断题', numeric_fill: '数值填空', expression_fill: '表达式填空' }
const canStart = computed(() => store.options && (store.config.chapter_ids.length || store.config.knowledge_point_codes.length) && store.questionTotal >= 5 && store.questionTotal <= 30)
onMounted(() => store.loadOptions().catch(() => {}))
async function begin() { await store.create(); router.push(`/apply/exam/sessions/${store.session.session_id}`) }
</script>
<template><AppShell><template #topbar-title>自主考试</template><main class="setup"><button class="back" @click="router.push('/apply')"><ArrowLeft :size="15" :stroke-width="1.75" />返回学以致用</button><p class="eyebrow">自主考试</p><h1 class="t-1">按你的目标生成一场考试</h1><p>考试中不显示答案、解析、提示或 AI 辅导，交卷后统一判卷。</p><p v-if="store.error" class="error" role="alert">{{store.error}}</p><section v-if="store.options" class="panel card card-pad"><fieldset><legend class="t-2">知识范围</legend><p class="range-hint">先点开单元，再勾选书本知识点；勾「整单元」可一次选中该单元全部内容。</p><KnowledgeRangePicker class="range" v-model:chapter-ids="store.config.chapter_ids" v-model:point-codes="store.config.knowledge_point_codes" :chapters="store.options.chapters" :points="store.options.knowledge_points" /></fieldset><fieldset><legend class="t-2">难度与时长</legend><div class="row"><label>最低难度<select v-model.number="store.config.difficulty_min"><option v-for="n in 5" :key="n" :value="n">{{n}}</option></select></label><label>最高难度<select v-model.number="store.config.difficulty_max"><option v-for="n in 5" :key="n" :value="n">{{n}}</option></select></label><label>考试时间<select v-model.number="store.config.duration_minutes"><option v-for="n in [30,45,60,90]" :key="n" :value="n">{{n}} 分钟</option></select></label></div></fieldset><fieldset><legend class="t-2">题型数量 <small>共 {{store.questionTotal}} 题</small></legend><div class="type-grid"><label v-for="t in store.options.question_types" :key="t.value"><span>{{labels[t.value]}} <small>可用 {{t.available}}</small></span><input v-model.number="store.config.question_type_counts[t.value]" type="number" inputmode="numeric" min="0" :max="Math.min(30,t.available)"></label></div></fieldset><footer><p v-if="store.questionTotal<5||store.questionTotal>30" class="hint">题量总和需为 5–30 题。</p><BaseButton variant="primary" size="lg" :disabled="!canStart||store.loading" @click="begin">{{store.loading?'正在生成…':'生成考试'}}</BaseButton></footer></section><p v-else-if="store.loading" role="status">正在读取正式题库…</p></main></AppShell></template>
<style scoped>.setup{max-width:960px;margin:0 auto;padding:32px 24px 72px}.back{display:inline-flex;align-items:center;gap:5px;border:0;background:none;color:var(--ink-2);padding:0;font:inherit;font-size:13.5px;font-weight:500;cursor:pointer}.back:hover{color:var(--ink-1)}.eyebrow{display:inline-flex;align-items:center;height:26px;padding:0 12px;border-radius:var(--r-pill);border:1px solid var(--border);background:var(--surface);font-size:12px;color:var(--ink-2);font-weight:500;box-shadow:var(--shadow-1);margin:10px 0 0}.setup h1{margin:6px 0 8px}.setup>p{color:var(--ink-2)}.panel{margin-top:22px}fieldset{border:0;padding:0;margin:0 0 28px}legend{margin-bottom:12px}.range-hint{margin:0 0 12px;color:var(--ink-3);font-size:13px}legend small,.type-grid small{font-size:13px;color:var(--ink-2);font-weight:400}.row,.type-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.row label,.type-grid label{display:grid;gap:7px;color:var(--ink-2)}select,input[type=number]{box-sizing:border-box;min-height:44px;border:1px solid var(--border-strong);border-radius:10px;background:var(--surface);color:var(--ink-1);padding:0 10px;font:inherit;transition:border-color .15s ease,box-shadow .15s ease}select:focus-visible,input[type=number]:focus-visible{outline:none;border-color:var(--brand);box-shadow:0 0 0 3px var(--brand-soft)}.type-grid{grid-template-columns:repeat(2,minmax(0,1fr))}footer{display:flex;align-items:center;justify-content:space-between;gap:16px}.error{color:var(--rose)!important}.hint{color:var(--ink-2)}@media(max-width:650px){.setup{padding:24px 16px 64px}.row,.type-grid{grid-template-columns:1fr}footer{align-items:stretch;flex-direction:column}}</style>
