<script setup>
import { computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { useExamStore } from '@/stores/examStore'
const router = useRouter(), store = useExamStore()
const labels = { choice: '选择题', judge: '判断题', numeric_fill: '数值填空', expression_fill: '表达式填空' }
const canStart = computed(() => store.options && (store.config.chapter_ids.length || store.config.knowledge_point_codes.length) && store.questionTotal >= 5 && store.questionTotal <= 30)
onMounted(() => store.loadOptions().catch(() => {}))
async function begin() { await store.create(); router.push(`/apply/exam/sessions/${store.session.session_id}`) }
</script>
<template><AppShell><template #topbar-title>自主考试</template><main class="setup"><button class="back" @click="router.push('/apply')">返回学以致用</button><p class="eyebrow">自主考试</p><h1>按你的目标生成一场考试</h1><p>考试中不显示答案、解析、提示或 AI 辅导，交卷后统一判卷。</p><p v-if="store.error" class="error" role="alert">{{store.error}}</p><section v-if="store.options" class="panel"><fieldset><legend>知识范围</legend><div class="checks"><label v-for="c in store.options.chapters" :key="c.id"><input v-model="store.config.chapter_ids" type="checkbox" :value="c.id">{{c.name}}</label></div><div class="checks points"><label v-for="p in store.options.knowledge_points" :key="p.code"><input v-model="store.config.knowledge_point_codes" type="checkbox" :value="p.code">{{p.name}}</label></div></fieldset><fieldset><legend>难度与时长</legend><div class="row"><label>最低难度<select v-model.number="store.config.difficulty_min"><option v-for="n in 5" :key="n" :value="n">{{n}}</option></select></label><label>最高难度<select v-model.number="store.config.difficulty_max"><option v-for="n in 5" :key="n" :value="n">{{n}}</option></select></label><label>考试时间<select v-model.number="store.config.duration_minutes"><option v-for="n in [30,45,60,90]" :key="n" :value="n">{{n}} 分钟</option></select></label></div></fieldset><fieldset><legend>题型数量 <small>共 {{store.questionTotal}} 题</small></legend><div class="type-grid"><label v-for="t in store.options.question_types" :key="t.value"><span>{{labels[t.value]}} <small>可用 {{t.available}}</small></span><input v-model.number="store.config.question_type_counts[t.value]" type="number" inputmode="numeric" min="0" :max="Math.min(30,t.available)"></label></div></fieldset><footer><p v-if="store.questionTotal<5||store.questionTotal>30" class="hint">题量总和需为 5–30 题。</p><button :disabled="!canStart||store.loading" @click="begin">{{store.loading?'正在生成…':'生成考试'}}</button></footer></section><p v-else-if="store.loading" role="status">正在读取正式题库…</p></main></AppShell></template>
<style scoped>.setup{max-width:960px;margin:0 auto;padding:32px 24px 72px}.back{min-height:44px;border:0;background:none;color:var(--accent);font:inherit;cursor:pointer}.eyebrow{color:var(--accent)!important;font-weight:600}.setup h1{margin:4px 0 8px}.setup>p{color:var(--text-secondary)}.panel{margin-top:24px;padding:24px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}fieldset{border:0;padding:0;margin:0 0 28px}legend{font-size:18px;font-weight:600;margin-bottom:12px}legend small,.type-grid small{font-size:13px;color:var(--text-secondary);font-weight:400}.checks{display:flex;flex-wrap:wrap;gap:10px 18px}.points{margin-top:14px}.checks label{min-height:44px;display:flex;align-items:center;gap:7px}.row,.type-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.row label,.type-grid label{display:grid;gap:7px;color:var(--text-secondary)}select,input[type=number]{box-sizing:border-box;min-height:44px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);padding:0 10px;font:inherit}.type-grid{grid-template-columns:repeat(2,minmax(0,1fr))}footer{display:flex;align-items:center;justify-content:space-between;gap:16px}footer button{min-height:44px;border:0;border-radius:var(--radius-sm);padding:0 20px;background:var(--accent);color:#fff;font:inherit;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.error{color:var(--danger)!important}.hint{color:var(--text-secondary)}@media(max-width:650px){.setup{padding:24px 16px 64px}.panel{padding:20px}.row,.type-grid{grid-template-columns:1fr}footer{align-items:stretch;flex-direction:column}}</style>
