<script setup>
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { notesApi, unwrapNote } from '@/api/notes'

const route = useRoute(), router = useRouter(), items = ref([]), loading = ref(false), error = ref(''), statusFilter=ref(sessionStorage.getItem('notes-status')||'active'), courseId=ref(sessionStorage.getItem('notes-course')||''), knowledgePointId=ref(route.query.knowledge_point_id || sessionStorage.getItem('notes-kp')||''), offset=ref(Number(sessionStorage.getItem('notes-offset')||0)), total=ref(0), limit=20
const canNext=computed(()=>offset.value+limit<total.value)
async function load() { loading.value = true; error.value = ''; try { const data=await unwrapNote(await notesApi.list({limit,offset:offset.value,status:statusFilter.value,course_id:courseId.value||undefined,knowledge_point_id:knowledgePointId.value||undefined})); items.value=data.items;total.value=data.total } catch (e) { error.value = e.message || '笔记加载失败' } finally { loading.value = false } }
function move(delta){offset.value=Math.max(0,offset.value+delta*limit);load()}
async function create() { loading.value = true; try { const note = await unwrapNote(await notesApi.create({ title: '未命名笔记' })); router.push(`/notes/${note.note_id}`) } catch (e) { error.value = e.message || '新建笔记失败' } finally { loading.value = false } }
async function archive(note){try{await unwrapNote(await notesApi.archive(note.note_id));await load()}catch(e){error.value=e.message||'归档失败'}}
async function remove(note){if(!window.confirm('移至回收站？可在保留期内恢复。'))return;try{await notesApi.remove(note.note_id);await load()}catch(e){error.value=e.message||'删除失败'}}
async function restore(note){try{await unwrapNote(await notesApi.restore(note.note_id));await load()}catch(e){error.value=e.message||'恢复失败'}}
function applyFilters(){offset.value=0;load()}watch([statusFilter,courseId,knowledgePointId,offset],()=>{sessionStorage.setItem('notes-status',statusFilter.value);sessionStorage.setItem('notes-course',courseId.value);sessionStorage.setItem('notes-kp',knowledgePointId.value);sessionStorage.setItem('notes-offset',String(offset.value));sessionStorage.setItem('notes-scroll',String(document.querySelector('.shell-content')?.scrollTop||0))});onMounted(async()=>{await load();requestAnimationFrame(()=>{const container=document.querySelector('.shell-content');if(container)container.scrollTop=Number(sessionStorage.getItem('notes-scroll')||0)})})
</script>
<template><AppShell><template #topbar-title>智能笔记</template><main class="page"><header><div><h1>我的笔记</h1><p>最近编辑的手写笔记。</p></div><button class="primary" :disabled="loading" @click="create">新建笔记</button></header><div class="filters"><label>状态 <select v-model="statusFilter" @change="applyFilters"><option value="active">进行中</option><option value="archived">已归档</option><option value="deleted">回收站</option></select></label><label>课程 ID <input v-model.trim="courseId" @change="applyFilters"></label><label>知识点 ID <input v-model.trim="knowledgePointId" @change="applyFilters"></label></div><p v-if="error" class="error">{{ error }}</p><p v-if="loading">正在加载…</p><section v-else class="notes"><article v-for="note in items" :key="note.note_id" class="note"><button @click="router.push(`/notes/${note.note_id}`)"><strong>{{ note.title }}</strong><span>版本 {{ note.current_revision }} · {{ new Date(note.updated_at).toLocaleString() }}</span></button><div class="actions"><button v-if="statusFilter==='active'" @click="archive(note)">归档</button><button v-if="statusFilter==='active'" @click="remove(note)">移至回收站</button><button v-if="statusFilter!=='active'" class="primary" @click="restore(note)">恢复笔记</button></div></article><div v-if="!items.length" class="empty"><h2>{{statusFilter==='deleted'?'回收站为空':'还没有笔记'}}</h2><p>{{statusFilter==='deleted'?'删除的笔记会在保留期后永久清理。':'从一页手写笔记开始。'}}</p><button v-if="statusFilter==='active'" class="primary" @click="create">新建第一篇笔记</button></div></section><nav v-if="total>limit" class="pager"><button :disabled="!offset" @click="move(-1)">上一页</button><span>{{offset+1}}–{{Math.min(offset+limit,total)}} / {{total}}</span><button :disabled="!canNext" @click="move(1)">下一页</button></nav></main></AppShell></template>
<style scoped>.page{max-width:960px;margin:auto;padding:36px 24px 72px}.page>header{display:flex;justify-content:space-between;align-items:center;gap:20px}.page h1{margin:0}.page p{color:var(--text-secondary)}button{min-height:42px;padding:0 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);cursor:pointer}.primary{background:var(--accent);border-color:var(--accent);color:#fff}.notes{display:grid;gap:12px;margin-top:24px}.note{text-align:left;display:grid;gap:6px;padding:18px}.note span{color:var(--text-secondary);font-size:13px}.empty{text-align:center;padding:48px;border:1px dashed var(--border-subtle);border-radius:var(--radius-lg)}.error{color:var(--danger)!important}@media(max-width:600px){.page{padding:24px 16px}.page>header{align-items:flex-start;flex-direction:column}}</style>
