<script setup>
import { computed, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { renderMarkdown } from '@/utils/markdown'
import { usePracticeStore } from '@/stores/practiceStore'
const route=useRoute(), router=useRouter(), store=usePracticeStore()
const q=computed(()=>store.currentQuestion), feedback=computed(()=>q.value&&store.feedback[q.value.question_id])
onMounted(async()=>{await store.loadSession(route.params.sessionId); if(store.session.status==='created') await store.start()})
async function submit(){await store.submitCurrent()}
async function finish(){await store.complete();router.push(`/apply/practice/sessions/${route.params.sessionId}/result`)}
</script>
<template><AppShell><template #topbar-title>专项练习 · {{store.currentIndex+1}}/{{store.session?.questions?.length||0}}</template><main v-if="q" class="runner"><header><span>即时反馈</span><span>已完成 {{Object.keys(store.feedback).length}} 题</span></header><p v-if="store.error" role="alert" class="error">{{store.error}}</p><section class="question"><div class="meta">第 {{q.position}} 题 · {{q.question_type}}</div><div class="math" v-html="renderMarkdown(q.content)"/><div v-if="q.question_type==='choice'" class="options"><label v-for="o in q.options||[]" :key="o.id"><input v-model="store.answers[q.question_id]" type="radio" :value="o.id" :disabled="!!feedback">{{o.id}}. <span v-html="renderMarkdown(o.text)"/></label></div><div v-else-if="q.question_type==='judge'" class="options"><label><input v-model="store.answers[q.question_id]" type="radio" value="true" :disabled="!!feedback">对</label><label><input v-model="store.answers[q.question_id]" type="radio" value="false" :disabled="!!feedback">错</label></div><input v-else v-model="store.answers[q.question_id]" :disabled="!!feedback" :placeholder="q.question_type==='numeric_fill'?'输入数值答案':'输入表达式，例如 x^2+1'"/></section><section v-if="feedback" class="feedback" :class="feedback.correct?'correct':'incorrect'"><strong>{{feedback.correct?'回答正确':'回答有误'}}</strong><p>正确答案：{{feedback.correct_answer}}</p><div v-if="feedback.analysis" class="math" v-html="renderMarkdown(feedback.analysis)"/></section><footer><button :disabled="store.currentIndex===0" @click="store.currentIndex--">上一题</button><button v-if="!feedback" class="primary" :disabled="store.loading || store.answers[q.question_id]===undefined || store.answers[q.question_id]===''" @click="submit">提交本题</button><button v-if="store.currentIndex<store.session.questions.length-1" class="primary" :disabled="!feedback" @click="store.currentIndex++">下一题</button><button v-else class="primary" :disabled="!feedback" @click="finish">完成练习</button></footer></main><p v-else class="loading">正在恢复练习…</p></AppShell></template>
<style scoped>.runner{max-width:920px;margin:0 auto;padding:28px 24px 88px}.runner>header{display:flex;justify-content:space-between;color:var(--text-secondary);font-size:14px}.question,.feedback{margin-top:18px;padding:24px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}.meta{color:var(--text-tertiary);font-size:14px;margin-bottom:14px}.math{line-height:1.75}.options{display:flex;flex-direction:column;gap:12px;margin-top:18px}.options label{min-height:36px}input:not([type=radio]){box-sizing:border-box;width:100%;min-height:42px;margin-top:18px;padding:8px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);font:inherit}.feedback.correct{border-left:4px solid var(--success)}.feedback.incorrect{border-left:4px solid var(--danger)}footer{display:flex;gap:12px;justify-content:space-between;margin-top:24px}button{min-height:44px;padding:0 18px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary);font:inherit;cursor:pointer}.primary{margin-left:auto;background:var(--accent);border-color:var(--accent);color:#fff}.error{color:var(--danger)}.loading{padding:32px}@media(max-width:600px){.runner{padding:20px 16px 80px}.question,.feedback{padding:18px}footer{flex-wrap:wrap}.primary{margin-left:0}}</style>
