<script setup>
import { onMounted, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { renderMarkdown } from '@/utils/markdown'
import { usePracticeStore } from '@/stores/practiceStore'
import { errorCategoryLabel } from '@/utils/errorCategories'
const route=useRoute(),router=useRouter(),store=usePracticeStore()
const expanded=ref({})
const toggle=(id)=>{expanded.value[id]=!expanded.value[id]}
const duration=(seconds)=>seconds==null?'未记录':`${Math.floor(seconds/60)} 分 ${seconds%60} 秒`
const typeLabel=(item)=>item.error_classification?.question_type||''
onMounted(()=>store.loadResult(route.params.sessionId))
</script>
<template><AppShell><template #topbar-title>专项练习结果</template><main v-if="store.result" class="result"><p class="eyebrow">本组练习完成</p><h1>{{store.result.correct}} / {{store.result.total}} 题正确</h1><p>用时 {{duration(store.result.duration_seconds)}} · 本次结果仅代表本组练习。</p><section><h2>知识点表现</h2><ul><li v-for="row in store.result.knowledge_breakdown" :key="row.knowledge_point_code"><span>{{row.knowledge_point_code}}</span><span>{{row.correct}} / {{row.total}}（{{Math.round(row.accuracy*100)}}%）</span></li></ul></section><section v-if="store.result.error_breakdown?.length"><h2>错因分布</h2><ul><li v-for="row in store.result.error_breakdown" :key="row.category"><span>{{errorCategoryLabel(row.category)}}</span><span>{{row.count}} 题</span></li></ul></section><section><h2>逐题回顾</h2><ul class="review"><li v-for="item in store.result.results" :key="item.question_id" :class="['review-item',item.correct?'ok':'bad']"><button class="review-head" :aria-expanded="expanded[item.question_id]?'true':'false'" @click="toggle(item.question_id)"><span class="badge">{{item.correct?'答对':'待改进'}}</span><span class="stem math" v-html="renderMarkdown(item.question_content||item.question_id)"/><span class="chevron" aria-hidden="true">{{expanded[item.question_id]?'收起':'展开'}}</span></button><div v-if="expanded[item.question_id]" class="review-body"><p><span class="label">你的答案</span>{{item.your_answer??'（未作答）'}}</p><p><span class="label">正确答案</span>{{item.correct_answer}}</p><p v-if="!item.correct&&item.error_category"><span class="label">错因</span>{{errorCategoryLabel(item.error_category)}}</p><div v-if="item.analysis"><span class="label">解析</span><div class="math" v-html="renderMarkdown(item.analysis)"/></div></div></li></ul></section><footer><button @click="router.push('/apply/practice')">按薄弱点再练</button><button class="primary" @click="router.push('/apply')">返回学以致用</button></footer></main><p v-else class="loading">正在加载结果…</p></AppShell></template>
<style scoped>.result{max-width:880px;margin:0 auto;padding:40px 24px 80px}.eyebrow{color:var(--accent);font-weight:600}.result h1{font-size:32px;margin:8px 0}.result>p:not(.eyebrow){color:var(--text-secondary)}section{padding:20px 0;border-bottom:1px solid var(--border-subtle)}h2{font-size:18px}ul{padding:0;list-style:none}li{display:flex;justify-content:space-between;padding:10px 0}.review .review-item{display:block;padding:0;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface);margin-top:10px;overflow:hidden}.review-head{display:flex;align-items:flex-start;gap:12px;width:100%;padding:14px 16px;border:0;background:transparent;text-align:left;font:inherit;cursor:pointer}.badge{flex-shrink:0;padding:2px 10px;border-radius:999px;font-size:13px}.ok .badge{background:var(--accent-soft);color:var(--success)}.bad .badge{background:var(--danger);color:#fff}.stem{flex:1;color:var(--text-primary);line-height:1.6;max-height:66px;overflow:hidden}.chevron{flex-shrink:0;color:var(--text-tertiary);font-size:13px}.review-body{padding:0 16px 16px 58px;display:grid;gap:8px;color:var(--text-primary)}.review-body .label{display:inline-block;min-width:64px;color:var(--text-tertiary);font-size:13px}.review-body .math{line-height:1.7;margin-top:2px}.ok .review-head .stem{color:var(--text-primary)}footer{display:flex;gap:12px;margin-top:28px}button{min-height:44px;padding:0 18px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);font:inherit;cursor:pointer}.primary{background:var(--accent);border-color:var(--accent);color:#fff}.loading{padding:32px}@media(max-width:600px){.result{padding:28px 16px 64px}.review-body{padding-left:16px}}</style>
