<script setup>
import { computed,onMounted } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import { usePracticeStore } from '@/stores/practiceStore'
const route=useRoute(),router=useRouter(),store=usePracticeStore()
const canStart=computed(()=>store.options&&(store.draft.chapter_ids.length||store.draft.knowledge_point_codes.length)),minutes=computed(()=>Math.max(1,Math.ceil(store.draft.question_count*1.5)))
const feedbackText=computed(()=>({immediate:'每题提交后反馈，答错可再试一次。',adaptive:'答错先给方向和诊断，逐步增加帮助。',deferred:'全部完成后统一反馈。'}[store.draft.behavior]))
onMounted(async()=>{await store.loadOptions().catch(()=>{});const requested=String(route.query.knowledge_points||route.query.knowledge_point||'').split(',').filter(Boolean);const code=requested[0];if(code&&store.options&&!store.options.knowledge_points?.some(p=>p.code===code)){for(const course of store.options.courses||[]){if(course.id===store.options.course_id)continue;const data=await store.loadOptions(course.id).catch(()=>null);if(data?.knowledge_points?.some(p=>p.code===code))break}}if(code&&store.options?.knowledge_points?.some(p=>p.code===code)){store.draft.knowledge_point_codes=requested.filter(x=>store.options.knowledge_points.some(p=>p.code===x));store.draft.chapter_ids=[]}})
async function begin(){await store.create();router.push({path:`/apply/practice/sessions/${store.session.session_id}`,query:route.query.return_to?{return_to:route.query.return_to}:{}})}
</script>
<template><AppShell><template #topbar-title>练习设置</template><main class="page"><button class="back" @click="router.push('/apply')">返回学以致用</button><h1>开始一次有反馈的练习</h1><p>先选范围、难度和题量；其余选项保持推荐值即可。</p><p v-if="store.error&&store.errorKind==='load'" class="error">题库加载失败：{{store.error}}</p><section v-if="store.options" class="panel"><h2>1. 练什么</h2><label class="label">章节</label><div class="checks"><label v-for="c in store.options.chapters" :key="c.id"><input v-model="store.draft.chapter_ids" type="checkbox" :value="c.id">{{c.name}}</label></div><label class="label">知识点</label><div class="checks"><label v-for="p in store.options.knowledge_points" :key="p.code"><input v-model="store.draft.knowledge_point_codes" type="checkbox" :value="p.code">{{p.name}}</label></div><div class="core"><label>难度<select v-model="store.draft.difficulty_band"><option :value="null">均衡难度</option><option :value="[1,2]">基础</option><option :value="[2,3]">适中</option><option :value="[4,5]">提升</option></select></label><label>题量<select v-model.number="store.draft.question_count"><option v-for="n in [5,10,15,20]" :key="n" :value="n">{{n}}题</option></select></label></div><details><summary>更多设置</summary><h2>题型</h2><div class="checks"><label v-for="t in store.options.question_types" :key="t.value"><input v-model="store.draft.question_types" type="checkbox" :value="t.value" :disabled="!t.available">{{t.value}}（{{t.available}}）</label></div><h2>顺序</h2><div class="segments"><label><input v-model="store.draft.order_mode" type="radio" value="random">随机</label><label><input v-model="store.draft.order_mode" type="radio" value="sequential">顺序</label></div><h2>反馈策略</h2><div class="segments"><label><input v-model="store.draft.behavior" type="radio" value="adaptive">自适应</label><label><input v-model="store.draft.behavior" type="radio" value="immediate">即时</label><label><input v-model="store.draft.behavior" type="radio" value="deferred">延后</label></div><p class="hint">{{feedbackText}}</p></details><div class="summary"><span>{{store.draft.question_count}}题 · 约{{minutes}}分钟</span><span>默认：{{store.draft.order_mode==='random'?'随机顺序':'顺序'}} · {{store.draft.behavior==='adaptive'?'自适应反馈':store.draft.behavior==='immediate'?'即时反馈':'统一反馈'}}</span></div><p v-if="store.error&&store.errorKind==='create'" class="error">创建失败：{{store.error}}</p><button class="primary" :disabled="!canStart||store.loading" @click="begin">开始练习</button></section><p v-else>正在加载题库…</p></main></AppShell></template>
<style scoped>.page{max-width:880px;margin:auto;padding:34px 24px 70px}.back{border:0;background:none;color:var(--accent);padding:0}.page>p{color:var(--text-secondary)}.panel{margin-top:24px;padding:26px;border:1px solid var(--border-subtle);border-radius:var(--radius-lg);background:var(--surface)}h2{font-size:18px;margin:22px 0 10px}.panel>h2:first-child{margin-top:0}.label{color:var(--text-secondary)}.checks{display:flex;flex-wrap:wrap;gap:10px 18px;margin:9px 0 20px}.core{display:grid;grid-template-columns:1fr 1fr;gap:16px}.core label{display:grid;gap:7px;color:var(--text-secondary)}select{min-height:42px;padding:0 10px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm);background:var(--surface);color:var(--text-primary)}details{margin-top:22px;padding-top:18px;border-top:1px solid var(--border-subtle)}summary{color:var(--accent);cursor:pointer;font-weight:600}.segments{display:flex;flex-wrap:wrap;gap:8px}.segments label{padding:10px 14px;border:1px solid var(--border-subtle);border-radius:var(--radius-sm)}.hint{color:var(--text-tertiary)}.summary{display:flex;justify-content:space-between;gap:15px;margin:24px 0 16px;padding:14px;background:var(--accent-soft);border-radius:var(--radius-sm)}button{min-height:44px;padding:0 18px;border-radius:var(--radius-sm);cursor:pointer}.primary{border:0;background:var(--accent);color:#fff}.error{color:var(--danger)!important}@media(max-width:600px){.core{grid-template-columns:1fr}.summary{align-items:flex-start;flex-direction:column}.panel{padding:18px}}</style>
