<script setup>
import { onMounted, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import AppShell from '@/components/shell/AppShell.vue'
import BaseButton from '@/components/ui/BaseButton.vue'
import { renderMarkdown } from '@/utils/markdown'
import { usePracticeStore } from '@/stores/practiceStore'
import { errorCategoryLabel } from '@/utils/errorCategories'
const route=useRoute(),router=useRouter(),store=usePracticeStore()
const expanded=ref({})
const toggle=(id)=>{expanded.value[id]=!expanded.value[id]}
const duration=(seconds)=>seconds==null?'未记录':`${Math.floor(seconds/60)} 分 ${seconds%60} 秒`
const typeLabel=(item)=>item.error_classification?.question_type||''
onMounted(()=>store.loadResult(route.params.sessionId))
</script>
<template><AppShell><template #topbar-title>专项练习结果</template><main v-if="store.result" class="result"><p class="eyebrow">本组练习完成</p><h1 class="t-1">{{store.result.correct}} / {{store.result.total}} 题正确</h1><p>用时 {{duration(store.result.duration_seconds)}} · 本次结果仅代表本组练习。</p><section class="card card-pad"><h2 class="t-2">知识点表现</h2><ul><li v-for="row in store.result.knowledge_breakdown" :key="row.knowledge_point_code"><span>{{row.knowledge_point_code}}</span><span>{{row.correct}} / {{row.total}}（{{Math.round(row.accuracy*100)}}%）</span></li></ul></section><section v-if="store.result.error_breakdown?.length" class="card card-pad"><h2 class="t-2">错因分布</h2><ul><li v-for="row in store.result.error_breakdown" :key="row.category"><span>{{errorCategoryLabel(row.category)}}</span><span>{{row.count}} 题</span></li></ul></section><section class="card card-pad"><h2 class="t-2">逐题回顾</h2><ul class="review"><li v-for="item in store.result.results" :key="item.question_id" :class="['review-item',item.correct?'ok':'bad']"><button class="review-head" :aria-expanded="expanded[item.question_id]?'true':'false'" @click="toggle(item.question_id)"><span class="badge">{{item.correct?'答对':'待改进'}}</span><span class="stem math" v-html="renderMarkdown(item.question_content||item.question_id)"/><span class="chevron" aria-hidden="true">{{expanded[item.question_id]?'收起':'展开'}}</span></button><div v-if="expanded[item.question_id]" class="review-body"><p><span class="label">你的答案</span>{{item.your_answer??'（未作答）'}}</p><p><span class="label">正确答案</span>{{item.correct_answer}}</p><p v-if="!item.correct&&item.error_category"><span class="label">错因</span>{{errorCategoryLabel(item.error_category)}}</p><div v-if="item.analysis"><span class="label">解析</span><div class="math" v-html="renderMarkdown(item.analysis)"/></div></div></li></ul></section><footer><BaseButton variant="secondary" size="lg" @click="router.push('/apply/practice')">按薄弱点再练</BaseButton><BaseButton variant="primary" size="lg" @click="router.push('/apply')">返回学以致用</BaseButton></footer></main><p v-else class="loading">正在加载结果…</p></AppShell></template>
<style scoped>.result{max-width:880px;margin:0 auto;padding:38px 24px 80px}.eyebrow{display:inline-flex;align-items:center;height:26px;padding:0 12px;border-radius:var(--r-pill);border:1px solid var(--border);background:var(--surface);font-size:12px;color:var(--ink-2);font-weight:500;box-shadow:var(--shadow-1)}.result h1{margin:12px 0 6px}.result>p:not(.eyebrow){color:var(--ink-2);margin:0}section{margin-top:16px}section h2{margin:0 0 10px}ul{padding:0;list-style:none;margin:0}li{display:flex;justify-content:space-between;gap:16px;padding:10px 0;border-bottom:1px dashed var(--border)}li:last-child{border-bottom:0}li span:first-child{color:var(--ink-2)}.review .review-item{display:block;padding:0;border:1px solid var(--border);border-radius:var(--r-m);background:var(--surface);margin-top:10px;overflow:hidden}.review-head{display:flex;align-items:flex-start;gap:12px;width:100%;padding:14px 16px;border:0;background:transparent;text-align:left;font:inherit;cursor:pointer}.review-head:hover{background:var(--surface-2)}.badge{flex-shrink:0;padding:3px 10px;border-radius:7px;font-size:12px;font-weight:600}.ok .badge{background:var(--green-soft);color:var(--green)}.bad .badge{background:var(--rose-soft);color:var(--rose)}.stem{flex:1;color:var(--ink-1);line-height:1.6;max-height:66px;overflow:hidden}.chevron{flex-shrink:0;color:var(--ink-3);font-size:13px}.review-body{padding:0 16px 16px 58px;display:grid;gap:8px;color:var(--ink-1)}.review-body .label{display:inline-block;min-width:64px;color:var(--ink-3);font-size:13px}.review-body .math{line-height:1.7;margin-top:2px}footer{display:flex;gap:12px;margin-top:28px}.loading{padding:32px}@media(max-width:600px){.result{padding:28px 16px 64px}.review-body{padding-left:16px}}</style>
